# Generated by Django 5.1.5 on 2026-08-22 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_stable_student_ordering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "Заполняется"), ("completed", "Пройден"), ("skipped", "Отложен")],
                        default="in_progress",
                        max_length=16,
                        verbose_name="Состояние",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Начат")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершён")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Онбординг",
                "verbose_name_plural": "Онбординг",
            },
        ),
        migrations.CreateModel(
            name="StudentGameState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("xp", models.PositiveIntegerField(default=0, verbose_name="Всего XP")),
                ("level", models.PositiveSmallIntegerField(default=1, verbose_name="Уровень")),
                ("streak_days", models.PositiveSmallIntegerField(default=0, verbose_name="Стрик, дней")),
                ("best_streak", models.PositiveSmallIntegerField(default=0, verbose_name="Лучший стрик")),
                ("last_active_on", models.DateField(blank=True, null=True, verbose_name="Последняя активность")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_state",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние ученика",
                "verbose_name_plural": "Состояния учеников",
            },
        ),
        migrations.CreateModel(
            name="OnboardingAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=32, verbose_name="Вопрос")),
                ("value", models.CharField(blank=True, max_length=250, verbose_name="Ответ")),
                ("target", models.CharField(blank=True, max_length=120, verbose_name="Целевое поле")),
                ("domain_code", models.CharField(blank=True, max_length=16, verbose_name="Домен")),
                ("is_confirmed", models.BooleanField(default=False, verbose_name="Подтверждено директором")),
                ("confirmed_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда подтверждено")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Отвечено")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_onboarding_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто подтвердил",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="engagement.onboardingsession",
                        verbose_name="Онбординг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ онбординга",
                "verbose_name_plural": "Ответы онбординга",
                "ordering": ("session", "id"),
                "indexes": [
                    models.Index(fields=["domain_code", "is_confirmed"], name="engagement__domain__cbc111_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("session", "question"), name="uniq_answer_per_question")
                ],
            },
        ),
        migrations.CreateModel(
            name="XPEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("task_done", "Задача роадмапа выполнена"),
                            ("exercise_solved", "Упражнение решено"),
                            ("mock_taken", "Пробный экзамен пройден"),
                            ("profile_section", "Раздел профиля заполнен"),
                            ("essay_submitted", "Эссе отправлено на проверку"),
                            ("onboarding_done", "Онбординг пройден"),
                        ],
                        max_length=32,
                        verbose_name="За что",
                    ),
                ),
                ("amount", models.PositiveSmallIntegerField(verbose_name="Сколько")),
                ("object_label", models.CharField(blank=True, max_length=64, verbose_name="Объект")),
                ("object_id", models.CharField(blank=True, max_length=32, verbose_name="Идентификатор объекта")),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="Пояснение")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Когда")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_events",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Начисление XP",
                "verbose_name_plural": "Начисления XP",
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["student", "-created_at"], name="engagement__student_e0a05b_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("object_id", ""), _negated=True),
                        fields=("student", "kind", "object_label", "object_id"),
                        name="uniq_xp_per_object",
                    )
                ],
            },
        ),
    ]
