# Generated by Django 5.1.5 on 2026-08-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xpevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("task_done", "Задача роадмапа выполнена"),
                    ("exercise_solved", "Упражнение решено"),
                    ("mock_taken", "Пробный экзамен пройден"),
                    ("profile_section", "Раздел профиля заполнен"),
                    ("essay_submitted", "Эссе отправлено на проверку"),
                    ("onboarding_done", "Онбординг пройден"),
                    ("material_approved", "Материал прошёл проверку"),
                ],
                max_length=32,
                verbose_name="За что",
            ),
        ),
    ]
