# Generated by Django 5.1.5 on 2026-08-31 12:21

import django.db.models.deletion
from django.db import migrations, models


def seed_questions(apps, schema_editor):
    """Шесть стартовых вопросов анкеты. Дальше их ведёт директор школы."""
    CareerQuestion = apps.get_model("engagement", "CareerQuestion")
    rows = (
        ("favourite_subjects", "Какие школьные предметы вам нравятся больше всего?", "Можно несколько", "text", "", 10),
        ("outside_school", "Чем вам нравится заниматься вне учёбы?", "Кружки, проекты, увлечения", "text", "", 20),
        ("easy_tasks", "Какие задачи даются вам легко?", "То, что получается само собой", "text", "", 30),
        ("dislikes", "Что вам точно не нравится делать?", "Это сужает выбор не меньше, чем любимое", "text", "", 40),
        ("in_ten_years", "Кем вы видите себя через десять лет?", "Своими словами, без правильных ответов", "text", "", 50),
        (
            "what_matters",
            "Что для вас важнее в будущей работе?",
            "Выберите одно",
            "choice",
            "Доход\nИнтерес к делу\nПольза для людей",
            60,
        ),
    )
    for code, text, hint, kind, options, order in rows:
        CareerQuestion.objects.get_or_create(
            code=code, defaults={"text": text, "hint": hint, "kind": kind, "options": options, "order": order}
        )


def unseed_questions(apps, schema_editor):
    CareerQuestion = apps.get_model("engagement", "CareerQuestion")
    CareerQuestion.objects.filter(answers__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0002_phase19_material_xp"),
        ("students", "0014_phase42_exam_types"),
        ("suggestions", "0007_phase41_plan_source"),
        ("universities", "0009_phase44_scholarships"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True, verbose_name="Код")),
                ("text", models.CharField(max_length=300, verbose_name="Вопрос")),
                ("hint", models.CharField(blank=True, max_length=250, verbose_name="Подсказка")),
                (
                    "kind",
                    models.CharField(
                        choices=[("text", "Свободный ответ"), ("choice", "Выбор из вариантов")],
                        default="text",
                        max_length=12,
                        verbose_name="Вид ответа",
                    ),
                ),
                (
                    "options",
                    models.TextField(blank=True, help_text="По одному в строке", verbose_name="Варианты ответа"),
                ),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
            ],
            options={
                "verbose_name": "Вопрос профтеста",
                "verbose_name_plural": "Вопросы профтеста",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CareerRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Разбор готов"), ("failed", "Не получился")],
                        default="done",
                        max_length=12,
                        verbose_name="Состояние",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Общий вывод")),
                ("error", models.CharField(blank=True, max_length=250, verbose_name="Что пошло не так")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Пройден")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_runs",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проход профтеста",
                "verbose_name_plural": "Проходы профтеста",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CareerDirection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
                ("title", models.CharField(max_length=150, verbose_name="Направление")),
                ("reasoning", models.TextField(blank=True, verbose_name="Почему подходит")),
                ("subjects", models.CharField(blank=True, max_length=300, verbose_name="Какие предметы нужны")),
                ("exams", models.CharField(blank=True, max_length=300, verbose_name="Какие экзамены нужны")),
                ("agreed_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда согласился")),
                (
                    "programs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="career_directions",
                        to="universities.program",
                        verbose_name="Программы справочника",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_directions",
                        to="suggestions.suggestion",
                        verbose_name="Предложение",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directions",
                        to="engagement.careerrun",
                        verbose_name="Проход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление профтеста",
                "verbose_name_plural": "Направления профтеста",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CareerAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField(blank=True, verbose_name="Ответ")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="engagement.careerquestion",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="engagement.careerrun",
                        verbose_name="Проход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ профтеста",
                "verbose_name_plural": "Ответы профтеста",
                "ordering": ("question__order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="careerrun",
            index=models.Index(fields=["student", "-created_at"], name="engagement__student_7f0c14_idx"),
        ),
        migrations.AddConstraint(
            model_name="careeranswer",
            constraint=models.UniqueConstraint(fields=("run", "question"), name="uniq_career_answer"),
        ),
        migrations.RunPython(seed_questions, unseed_questions),
    ]
