# Generated by Django 5.1.5 on 2026-08-31 12:43

import django.db.models.deletion
from django.db import migrations, models


def seed_badges(apps, schema_editor):
    """Стартовый набор бейджей. Дальше их ведёт директор школы строками."""
    Badge = apps.get_model("engagement", "Badge")
    rows = (
        ("profile_filled", "Рассказал о себе", "Заполнены разделы профиля", "profile_sections", 3, "person", 10),
        ("first_plan", "Первый план", "Создан план по вузу", "plans_created", 1, "target", 20),
        ("first_essay", "Первое эссе", "Начато первое эссе", "essays_started", 1, "doc", 30),
        ("hundred_answers", "Сто заданий", "Решено сто заданий банка", "exercises_solved", 100, "checklist", 40),
        ("week_streak", "Семь дней подряд", "Семь дней подряд с действиями", "streak_days", 7, "star", 50),
        ("shared_material", "Поделился разбором", "Материал прошёл проверку", "materials_approved", 1, "openbook", 60),
        ("first_mock", "Пробный пройден", "Пройден пробный экзамен", "mocks_taken", 1, "trophy", 70),
        ("onboarding", "Начало положено", "Пройдена анкета первого входа", "onboarding_done", 1, "branch", 80),
        ("reader", "Читатель", "Прочитано пять материалов раздела «Ресурсы»", "resources_read", 5, "book", 90),
        ("quiz_player", "Игрок", "Сыграно пять матчей квиза", "quiz_matches", 5, "medal", 100),
    )
    for code, name, description, metric, threshold, icon, order in rows:
        Badge.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "description": description,
                "metric": metric,
                "threshold": threshold,
                "icon": icon,
                "order": order,
            },
        )


def unseed_badges(apps, schema_editor):
    Badge = apps.get_model("engagement", "Badge")
    Badge.objects.filter(awards__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0003_phase45_resources_and_career"),
        ("students", "0014_phase42_exam_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True, verbose_name="Код")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("description", models.CharField(blank=True, max_length=250, verbose_name="Описание")),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("tasks_done", "Выполненные задачи роадмапа"),
                            ("exercises_solved", "Решённые упражнения"),
                            ("mocks_taken", "Пройденные пробные экзамены"),
                            ("profile_sections", "Заполненные разделы профиля"),
                            ("essays_started", "Начатые эссе"),
                            ("onboarding_done", "Пройденная анкета первого входа"),
                            ("materials_approved", "Материалы, прошедшие проверку"),
                            ("resources_read", "Прочитанные материалы раздела «Ресурсы»"),
                            ("streak_days", "Дней подряд с действиями"),
                            ("plans_created", "Созданные планы по вузам"),
                            ("quiz_matches", "Сыгранные матчи квиза"),
                            ("documents_uploaded", "Загруженные документы портфолио"),
                        ],
                        max_length=32,
                        verbose_name="Что считаем",
                    ),
                ),
                ("threshold", models.PositiveIntegerField(default=1, verbose_name="Сколько нужно")),
                ("icon", models.CharField(blank=True, default="medal", max_length=32, verbose_name="Иконка")),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
            ],
            options={
                "verbose_name": "Бейдж",
                "verbose_name_plural": "Бейджи",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="BadgeAward",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Получен")),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="engagement.badge",
                        verbose_name="Бейдж",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полученный бейдж",
                "verbose_name_plural": "Полученные бейджи",
                "ordering": ("-created_at",),
                "constraints": [models.UniqueConstraint(fields=("student", "badge"), name="uniq_badge_per_student")],
            },
        ),
        migrations.RunPython(seed_badges, unseed_badges),
    ]
