# Generated by Django 5.1.5 on 2026-09-01 10:45

from django.db import migrations, models


def seed_rules(apps, schema_editor):
    """Стартовые правила карусели и обзвона.

    Это справочник, а не выдуманные ученики (инвариант №8): без правил
    карусель пуста с первого дня, а список «кому позвонить» не собрать
    вовсе. Школа меняет слова и пороги на своих экранах, без выката.
    """
    HomeCue = apps.get_model("engagement", "HomeCue")
    cues = (
        (
            "portfolio",
            "portfolio_gap",
            "Ваши достижения ещё не в портфолио",
            "Проекты, конкурсы и волонтёрство вузы смотрят наравне с баллами.",
            "Добавить достижение",
            "/my-data",
            "brand",
            10,
        ),
        (
            "exam-goal",
            "exam_goal_gap",
            "До цели по экзамену осталось немного",
            "Разберите слабые темы — тренировка на сегодня уже собрана.",
            "Открыть подготовку",
            "/prep",
            "ink",
            20,
        ),
        (
            "scholarships",
            "scholarship_deadline",
            "Стипендии с ближайшим дедлайном",
            "Проверьте, какие из них подходят под ваш профиль и специальность.",
            "Посмотреть",
            "/scholarships",
            "teal",
            30,
        ),
        (
            "universities",
            "no_universities",
            "Список вузов пока пуст",
            "Пока в списке нет программ, план и сроки собрать не из чего.",
            "Открыть каталог",
            "/catalog",
            "indigo",
            40,
        ),
        (
            "plan",
            "plan_idle",
            "План стоит на месте",
            "Ближайшие задачи ждут — отметьте сделанное или сдвиньте сроки.",
            "Открыть план",
            "/plan",
            "brand",
            50,
        ),
        (
            "documents",
            "documents_missing",
            "Документы ещё не собраны",
            "Аттестат, транскрипт и сертификаты понадобятся при подаче.",
            "Загрузить документы",
            "/my-data",
            "indigo",
            60,
        ),
    )
    for code, condition, title, description, action, path, tone, order in cues:
        HomeCue.objects.get_or_create(
            code=code,
            defaults={
                "condition": condition,
                "title": title,
                "description": description,
                "action_label": action,
                "action_path": path,
                "tone": tone,
                "order": order,
            },
        )

    CallRule = apps.get_model("engagement", "CallRule")
    rules = (
        ("attendance", "absences", "низкая посещаемость", "now", 80, 10),
        ("mock-drop", "mock_drop", "просел по пробным", "now", 0.5, 20),
        ("inactive", "inactive", "не заходил в систему", "today", 21, 30),
        ("deadline", "missed_deadline", "пропустил дедлайн", "today", 1, 40),
        ("no-contact", "no_contact", "нет контактов родителей", "week", 1, 50),
    )
    for code, condition, reason, urgency, threshold, order in rules:
        CallRule.objects.get_or_create(
            code=code,
            defaults={
                "condition": condition,
                "reason": reason,
                "urgency": urgency,
                "threshold": threshold,
                "order": order,
            },
        )


def unseed_rules(apps, schema_editor):
    apps.get_model("engagement", "HomeCue").objects.all().delete()
    apps.get_model("engagement", "CallRule").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0005_phase48_career_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True, verbose_name="Код")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("absences", "Пропуски занятий"),
                            ("mock_drop", "Просел по пробным"),
                            ("inactive", "Не заходил в систему"),
                            ("missed_deadline", "Пропустил дедлайн"),
                            ("no_contact", "Нет контактов родителей"),
                        ],
                        max_length=32,
                        verbose_name="Условие",
                    ),
                ),
                ("reason", models.CharField(max_length=120, verbose_name="Причина одной фразой")),
                (
                    "urgency",
                    models.CharField(
                        choices=[("now", "Срочно"), ("today", "Сегодня"), ("week", "На неделе")],
                        default="today",
                        max_length=8,
                        verbose_name="Срочность",
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=1, default=1, max_digits=6, verbose_name="Порог")),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
            ],
            options={
                "verbose_name": "Правило обзвона",
                "verbose_name_plural": "Правила обзвона",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="HomeCue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True, verbose_name="Код")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("portfolio_gap", "Портфолио заполнено не до конца"),
                            ("exam_goal_gap", "До цели по экзамену не хватает"),
                            ("scholarship_deadline", "Стипендии с ближайшим дедлайном не просмотрены"),
                            ("plan_idle", "План не открывали неделю"),
                            ("no_universities", "Список вузов пуст"),
                            ("documents_missing", "Документы не загружены"),
                        ],
                        max_length=32,
                        verbose_name="Условие",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Заголовок")),
                ("description", models.CharField(blank=True, max_length=250, verbose_name="Описание")),
                ("action_label", models.CharField(max_length=60, verbose_name="Подпись кнопки")),
                ("action_path", models.CharField(max_length=120, verbose_name="Куда ведёт кнопка")),
                (
                    "tone",
                    models.CharField(
                        choices=[("brand", "Оранжевый"), ("ink", "Графит"), ("teal", "Бирюза"), ("indigo", "Индиго")],
                        default="brand",
                        max_length=16,
                        verbose_name="Цвет карточки",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
            ],
            options={
                "verbose_name": "Сюжет главной",
                "verbose_name_plural": "Сюжеты главной",
                "ordering": ("order", "id"),
            },
        ),
        migrations.RunPython(seed_rules, unseed_rules),
    ]
