# Generated by Django 5.2.17 on 2026-09-09 17:26

from django.db import migrations, models

#: Пять видов писем на двух языках. Формулировки школьные и правятся
#: администратором — здесь только то, с чего школа начинает.
SEED = [
    (
        "document",
        "ru",
        "{ученик}: не хватает документов",
        "Здравствуйте!\n\n"
        "У {ученик} ({группа}) не хватает документов: {просим}.\n"
        "Просим прислать до {срок}.\n\n"
        "С уважением,\n{куратор}",
    ),
    (
        "document",
        "kk",
        "{ученик}: құжаттар жетіспейді",
        "Сәлеметсіз бе!\n\n"
        "{ученик} ({группа}) құжаттары толық емес: {просим}.\n"
        "{срок} дейін жіберуіңізді сұраймыз.\n\n"
        "Құрметпен,\n{куратор}",
    ),
    (
        "goal",
        "ru",
        "{ученик}: цель по экзамену",
        "Здравствуйте!\n\n"
        "У {ученик} ({группа}) не поставлена цель по экзамену: {просим}.\n"
        "Просим определиться до {срок}.\n\n"
        "С уважением,\n{куратор}",
    ),
    (
        "goal",
        "kk",
        "{ученик}: емтихан мақсаты",
        "Сәлеметсіз бе!\n\n"
        "{ученик} ({группа}) емтихан бойынша мақсаты қойылмаған: {просим}.\n"
        "{срок} дейін шешуіңізді сұраймыз.\n\n"
        "Құрметпен,\n{куратор}",
    ),
    (
        "mock",
        "ru",
        "{ученик}: пробный экзамен",
        "Здравствуйте!\n\n"
        "{ученик} ({группа}) не был на пробном экзамене: {просим}.\n"
        "Ближайшая дата — {срок}.\n\n"
        "С уважением,\n{куратор}",
    ),
    (
        "mock",
        "kk",
        "{ученик}: сынақ емтихан",
        "Сәлеметсіз бе!\n\n"
        "{ученик} ({группа}) сынақ емтиханға қатыспады: {просим}.\n"
        "Жақын күні — {срок}.\n\n"
        "Құрметпен,\n{куратор}",
    ),
    (
        "task",
        "ru",
        "{ученик}: задача не выполнена",
        "Здравствуйте!\n\n"
        "У {ученик} ({группа}) осталась невыполненная задача: {просим}.\n"
        "Срок — {срок}.\n\n"
        "С уважением,\n{куратор}",
    ),
    (
        "task",
        "kk",
        "{ученик}: тапсырма орындалмаған",
        "Сәлеметсіз бе!\n\n"
        "{ученик} ({группа}) орындалмаған тапсырмасы бар: {просим}.\n"
        "Мерзімі — {срок}.\n\n"
        "Құрметпен,\n{куратор}",
    ),
    (
        "free",
        "ru",
        "{ученик}: сообщение из школы",
        "Здравствуйте!\n\n{просим}\n\nС уважением,\n{куратор}",
    ),
    (
        "free",
        "kk",
        "{ученик}: мектептен хабарлама",
        "Сәлеметсіз бе!\n\n{просим}\n\nҚұрметпен,\n{куратор}",
    ),
]


def seed(apps, schema_editor):
    """Завести шаблоны. Уже заведённые не трогаем: школа их правит."""
    MailTemplate = apps.get_model("engagement", "MailTemplate")
    for kind, language, subject, body in SEED:
        MailTemplate.objects.get_or_create(
            kind=kind,
            language=language,
            defaults={"subject": subject, "body": body},
        )


def unseed(apps, schema_editor):
    MailTemplate = apps.get_model("engagement", "MailTemplate")
    MailTemplate.objects.filter(kind__in={k for k, *_ in SEED}).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0006_phase49"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("document", "Документы"),
                            ("goal", "Цель по экзамену"),
                            ("mock", "Пробник"),
                            ("task", "Задача"),
                            ("free", "Произвольное"),
                        ],
                        max_length=16,
                        verbose_name="Вид письма",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ru", "Русский"), ("kk", "Казахский")],
                        default="ru",
                        max_length=2,
                        verbose_name="Язык",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Тема")),
                ("body", models.TextField(verbose_name="Текст")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменён")),
            ],
            options={
                "verbose_name": "Шаблон письма",
                "verbose_name_plural": "Шаблоны писем",
                "ordering": ("kind", "language"),
                "constraints": [models.UniqueConstraint(fields=("kind", "language"), name="unique_mail_template")],
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
