# Generated by Django 5.2.17 on 2026-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0007_phase66"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="metric",
            field=models.CharField(
                choices=[
                    ("tasks_done", "Выполненные задачи роадмапа"),
                    ("exercises_solved", "Решённые упражнения"),
                    ("mocks_taken", "Пройденные пробные экзамены"),
                    ("profile_sections", "Заполненные разделы профиля"),
                    ("essays_started", "Начатые эссе"),
                    ("onboarding_done", "Пройденная анкета первого входа"),
                    ("materials_approved", "Материалы, прошедшие проверку"),
                    ("resources_read", "Прочитанные материалы раздела «Ресурсы»"),
                    ("streak_days", "Дней подряд с действиями"),
                    ("plans_created", "Созданные планы по вузам"),
                    ("documents_uploaded", "Загруженные документы портфолио"),
                ],
                max_length=32,
                verbose_name="Что считаем",
            ),
        ),
    ]
