# Generated by Django 5.2.17 on 2026-09-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0008_badge_metric_without_quiz"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MailTemplate",
        ),
    ]
