# Generated by Django 5.2.17 on 2026-09-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0010_xp_for_homework_on_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="metric",
            field=models.CharField(
                choices=[
                    ("tasks_done", "Выполненные задачи роадмапа"),
                    ("exercises_solved", "Решённые упражнения"),
                    ("mocks_taken", "Пройденные Mock Test онлайн"),
                    ("profile_sections", "Заполненные разделы профиля"),
                    ("essays_started", "Начатые эссе"),
                    ("onboarding_done", "Пройденная анкета первого входа"),
                    ("materials_approved", "Материалы, прошедшие проверку"),
                    ("resources_read", "Прочитанные материалы раздела «Ресурсы»"),
                    ("streak_days", "Дней подряд с действиями"),
                    ("plans_created", "Созданные планы по вузам"),
                    ("documents_uploaded", "Загруженные документы портфолио"),
                ],
                max_length=32,
                verbose_name="Что считаем",
            ),
        ),
        migrations.AlterField(
            model_name="callrule",
            name="condition",
            field=models.CharField(
                choices=[
                    ("absences", "Пропуски занятий"),
                    ("mock_drop", "Просел по Mock Test"),
                    ("inactive", "Не заходил в систему"),
                    ("missed_deadline", "Пропустил дедлайн"),
                    ("no_contact", "Нет контактов родителей"),
                ],
                max_length=32,
                verbose_name="Условие",
            ),
        ),
        migrations.AlterField(
            model_name="xpevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("task_done", "Задача роадмапа выполнена"),
                    ("exercise_solved", "Упражнение решено"),
                    ("mock_taken", "Mock Test онлайн пройден"),
                    ("profile_section", "Раздел профиля заполнен"),
                    ("essay_submitted", "Эссе отправлено на проверку"),
                    ("onboarding_done", "Онбординг пройден"),
                    ("homework_on_time", "ДЗ сдано в срок"),
                    ("material_approved", "Материал прошёл проверку"),
                ],
                max_length=32,
                verbose_name="За что",
            ),
        ),
    ]
