# Generated by Django 5.1.5 on 2026-08-21 07:08

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("full_name", models.CharField(blank=True, max_length=200, verbose_name="ФИО")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Ученик"),
                            ("director_behavior", "Директор школы — профиль и дисциплина"),
                            ("director_admission", "Директор по поступлению"),
                            ("director_exam", "Академический директор"),
                            ("director_talent", "Директор талантов"),
                            ("director_sport", "Директор спорта"),
                            ("admin", "Администратор"),
                        ],
                        default="student",
                        max_length=32,
                        verbose_name="Роль",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Доступ в админку")),
                ("date_joined", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ("email",),
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("entra", "Microsoft Entra ID"),
                            ("email_link", "Одноразовая ссылка на почту"),
                            ("local", "Локальный пароль"),
                        ],
                        max_length=32,
                        verbose_name="Провайдер",
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255, verbose_name="Внешний идентификатор")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("is_primary", models.BooleanField(default=False, verbose_name="Основная")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("last_login_at", models.DateTimeField(blank=True, null=True, verbose_name="Последний вход")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Идентичность",
                "verbose_name_plural": "Идентичности",
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "email"), name="uniq_identity_provider_email"),
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("provider", "external_id"),
                        name="uniq_identity_provider_external_id",
                    ),
                ],
            },
        ),
    ]
