# Generated by Django 5.1.5 on 2026-08-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicLinkToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="Email")),
                ("token_hash", models.CharField(max_length=64, unique=True, verbose_name="Хеш токена")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="Использован")),
            ],
            options={
                "verbose_name": "Одноразовая ссылка",
                "verbose_name_plural": "Одноразовые ссылки",
                "ordering": ("-created_at",),
            },
        ),
    ]
