# Generated by Django 5.1.5 on 2026-08-22 11:51

from django.db import migrations, models


def entra_identities_become_password(apps, schema_editor):
    """Прежние идентичности переезжают на провайдер `password`.

    Внешнего входа больше нет, но сами идентичности нужны: по ним человек
    узнаётся, и на них завязаны одноразовые ссылки выпускников.
    """
    Identity = apps.get_model("accounts", "Identity")
    for old in ("entra", "local"):
        for identity in Identity.objects.filter(provider=old):
            # почта уже могла быть заведена как парольная — тогда дубль не нужен
            if Identity.objects.filter(provider="password", email=identity.email).exists():
                identity.delete()
                continue
            identity.provider = "password"
            identity.external_id = ""
            identity.save(update_fields=["provider", "external_id"])


def back_to_entra(apps, schema_editor):
    """Обратный переезд неточен: какая идентичность была из Entra, уже не видно."""
    Identity = apps.get_model("accounts", "Identity")
    Identity.objects.filter(provider="password").update(provider="local")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_magiclinktoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclinktoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Вход по ссылке"),
                    ("invite", "Приглашение: установить пароль"),
                    ("reset", "Сброс пароля"),
                ],
                default="login",
                max_length=16,
                verbose_name="Назначение",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=True, verbose_name="Требуется сменить пароль"),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Пароль сменён"),
        ),
        migrations.AddField(
            model_name="user",
            name="sees_whole_school",
            field=models.BooleanField(default=False, verbose_name="Видит всю школу"),
        ),
        migrations.AlterField(
            model_name="identity",
            name="provider",
            field=models.CharField(
                choices=[("password", "Почта и пароль"), ("email_link", "Одноразовая ссылка на почту")],
                max_length=32,
                verbose_name="Провайдер",
            ),
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="Email")),
                ("ip", models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name="Адрес")),
                ("successful", models.BooleanField(default=False, verbose_name="Удачная")),
                ("reason", models.CharField(blank=True, max_length=64, verbose_name="Причина отказа")),
                ("user_agent", models.CharField(blank=True, max_length=250, verbose_name="Клиент")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Когда")),
            ],
            options={
                "verbose_name": "Попытка входа",
                "verbose_name_plural": "Попытки входа",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["email", "-created_at"], name="accounts_lo_email_f32d13_idx"),
                    models.Index(fields=["ip", "-created_at"], name="accounts_lo_ip_f55ee4_idx"),
                ],
            },
        ),
            migrations.RunPython(entra_identities_become_password, back_to_entra),
    ]
