# Generated by Django 5.1.5 on 2026-08-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_password_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("kk", "Қазақша"), ("en", "English")],
                default="ru",
                max_length=2,
                verbose_name="Язык",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sidebar_collapsed",
            field=models.BooleanField(default=False, verbose_name="Сайдбар свёрнут"),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("light", "Светлая"), ("dark", "Тёмная"), ("system", "Как в системе")],
                default="system",
                max_length=8,
                verbose_name="Тема",
            ),
        ),
    ]
