# Generated by Django 5.1.5 on 2026-08-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_language_user_sidebar_collapsed_user_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_password_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Временный пароль действует до"),
        ),
    ]
