# Generated by Django 5.1.15 on 2026-09-08 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_phase36_loginattempt_cleared"),
        ("students", "0015_phase59"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Ученик"),
                    ("director_behavior", "Директор школы — профиль и дисциплина"),
                    ("director_admission", "Директор по поступлению"),
                    ("director_exam", "Академический директор"),
                    ("director_talent", "Директор талантов"),
                    ("director_sport", "Директор спорта"),
                    ("curator", "Куратор"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=32,
                verbose_name="Роль",
            ),
        ),
        migrations.CreateModel(
            name="CuratorAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("since", models.DateField(verbose_name="Действует с")),
                ("until", models.DateField(blank=True, null=True, verbose_name="Действует до")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто назначил",
                    ),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curator_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Куратор",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curator_assignments",
                        to="students.studygroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение куратора",
                "verbose_name_plural": "Назначения кураторов",
                "ordering": ("-since", "-id"),
                "indexes": [models.Index(fields=["curator", "until"], name="accounts_cu_curator_b5c84d_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("until__isnull", True)),
                        fields=("group",),
                        name="one_open_curator_per_group",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("until__isnull", True), ("until__gt", models.F("since")), _connector="OR"),
                        name="curator_until_after_since",
                    ),
                ],
            },
        ),
    ]
