# Generated by Django 5.2.17 on 2026-09-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_phase60"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="link_identity_dismissed",
            field=models.BooleanField(default=False, verbose_name="Предложение о личной почте закрыто"),
        ),
    ]
