# Generated by Django 5.2.17 on 2026-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_phase75"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_fictional",
            field=models.BooleanField(default=False, verbose_name="Вымышленный"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Ученик"),
                    ("director_behavior", "Директор школы — профиль и дисциплина"),
                    ("director_admission", "Директор по поступлению"),
                    ("director_exam", "Академический директор"),
                    ("director_talent", "Директор талантов"),
                    ("director_sport", "Директор спорта"),
                    ("curator", "Куратор"),
                    ("teacher", "Учитель"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=32,
                verbose_name="Роль",
            ),
        ),
    ]
