# Generated by Django 5.2.17 on 2026-10-07 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_language_of_group_and_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailDayBudget",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False, verbose_name="Сутки UTC")),
            ],
            options={
                "verbose_name": "Дневной бюджет писем",
            },
        ),
        migrations.CreateModel(
            name="InviteMail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor_name", models.CharField(blank=True, max_length=254, verbose_name="Кто выдал")),
                ("address", models.EmailField(max_length=254, verbose_name="Адрес письма")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("invite", "Приглашение"),
                            ("reset", "Сброс пароля"),
                            ("login", "Вход по ссылке"),
                            ("confirm", "Подтверждение почты"),
                            ("temp_password", "Временный пароль"),
                        ],
                        max_length=20,
                        verbose_name="Назначение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("sending", "Отправляется"),
                            ("sent", "Отправлено"),
                            ("failed", "Не отправлено"),
                            ("cancelled", "Отменено"),
                        ],
                        max_length=12,
                        verbose_name="Состояние",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Создано")),
                ("scheduled_at", models.DateTimeField(blank=True, null=True, verbose_name="Не раньше")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Начало отправки")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершено")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Отправлено")),
                ("error", models.TextField(blank=True, verbose_name="Причина")),
                ("bulk", models.BooleanField(default=False, verbose_name="Массовое приглашение")),
                ("force", models.BooleanField(default=False, verbose_name="Повторная отправка разрешена")),
                ("uncertain", models.BooleanField(default=False, verbose_name="Результат отправки неизвестен")),
                ("cancelled_by_name", models.CharField(blank=True, max_length=254, verbose_name="Кто отменил")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_access_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_access_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.magiclinktoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invite_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Письмо с доступом",
                "verbose_name_plural": "Письма с доступом",
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(fields=["status", "scheduled_at"], name="access_mail_queue"),
                    models.Index(fields=["user", "status", "sent_at"], name="access_mail_history"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("bulk", True), ("status__in", ["queued", "sending"])),
                        fields=("user",),
                        name="one_pending_invite_per_user",
                    )
                ],
            },
        ),
    ]
