# Generated by Django 5.1.5 on 2026-08-21 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=16, unique=True, verbose_name="Код")),
                ("grade", models.PositiveSmallIntegerField(verbose_name="Класс")),
                ("curator", models.CharField(blank=True, max_length=200, verbose_name="Куратор")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "Учебная группа",
                "verbose_name_plural": "Учебные группы",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("middle_name", models.CharField(blank=True, max_length=100, verbose_name="Отчество")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("grade", models.PositiveSmallIntegerField(verbose_name="Класс")),
                ("graduation_year", models.PositiveSmallIntegerField(verbose_name="Год выпуска")),
                ("is_active", models.BooleanField(default=True, verbose_name="Учится")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учётная запись",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="students.studygroup",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="SportProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sport_kind", models.CharField(blank=True, max_length=100, verbose_name="Вид спорта")),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("school", "Школьный"),
                            ("city", "Городской"),
                            ("regional", "Областной"),
                            ("national", "Республиканский"),
                            ("international", "Международный"),
                        ],
                        max_length=16,
                        verbose_name="Уровень",
                    ),
                ),
                ("rank", models.CharField(blank=True, max_length=50, verbose_name="Разряд")),
                ("leadership_role", models.CharField(blank=True, max_length=100, verbose_name="Лидерская роль")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sport",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль: спорт",
                "verbose_name_plural": "Профили: спорт",
            },
        ),
        migrations.CreateModel(
            name="ExamProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "ielts_current",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="IELTS текущий"
                    ),
                ),
                (
                    "ielts_target",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="IELTS цель"
                    ),
                ),
                ("sat_current", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="SAT текущий")),
                ("sat_target", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="SAT цель")),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Часов в неделю"),
                ),
                ("teacher", models.CharField(blank=True, max_length=150, verbose_name="Преподаватель")),
                ("gpa", models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="GPA")),
                ("next_mock_date", models.DateField(blank=True, null=True, verbose_name="Следующий мок")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль: экзамены",
                "verbose_name_plural": "Профили: экзамены",
            },
        ),
        migrations.CreateModel(
            name="BehaviorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attendance_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Посещаемость, %"),
                ),
                ("remarks_count", models.PositiveSmallIntegerField(default=0, verbose_name="Замечания")),
                (
                    "homework_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Выполнение заданий, %"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("can_execute", "Работает самостоятельно"),
                            ("needs_supervision", "Нужен контроль"),
                            ("critical", "Ежедневный контроль"),
                        ],
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий куратора")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль: дисциплина",
                "verbose_name_plural": "Профили: дисциплина",
            },
        ),
        migrations.CreateModel(
            name="AdmissionProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_country", models.CharField(blank=True, max_length=100, verbose_name="Целевая страна")),
                ("target_major", models.CharField(blank=True, max_length=150, verbose_name="Специальность")),
                ("has_common_app", models.BooleanField(default=False, verbose_name="Common App заведён")),
                (
                    "has_application_account",
                    models.BooleanField(default=False, verbose_name="Application account заведён"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A — готов к подаче"),
                            ("B", "B — требует подготовки"),
                            ("C", "C — критический"),
                        ],
                        max_length=1,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль: поступление",
                "verbose_name_plural": "Профили: поступление",
            },
        ),
        migrations.CreateModel(
            name="TalentProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "main_track",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("olympiad", "Олимпиады"),
                            ("research", "Research"),
                            ("startup", "Startup"),
                            ("leadership", "Leadership"),
                            ("volunteering", "Volunteering"),
                            ("competition", "Competition"),
                        ],
                        max_length=32,
                        verbose_name="Основной трек",
                    ),
                ),
                (
                    "portfolio_status",
                    models.CharField(
                        blank=True,
                        choices=[("strong", "Сильное"), ("medium", "Среднее"), ("weak", "Слабое")],
                        max_length=16,
                        verbose_name="Статус портфолио",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль: таланты",
                "verbose_name_plural": "Профили: таланты",
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("IELTS", "IELTS"), ("TOEFL", "TOEFL"), ("SAT", "SAT"), ("ACT", "ACT")],
                        max_length=8,
                        verbose_name="Экзамен",
                    ),
                ),
                (
                    "attempt_format",
                    models.CharField(
                        choices=[("mock", "Мок"), ("official", "Официальный")], max_length=8, verbose_name="Формат"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True, verbose_name="Общий балл"
                    ),
                ),
                (
                    "listening",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Listening"
                    ),
                ),
                (
                    "reading",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Reading"),
                ),
                (
                    "writing",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Writing"),
                ),
                (
                    "speaking",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Speaking"),
                ),
                ("math", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Math")),
                ("verbal", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Verbal")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка экзамена",
                "verbose_name_plural": "Попытки экзаменов",
                "ordering": ("-date",),
                "indexes": [
                    models.Index(fields=["student", "exam_type", "-date"], name="students_ex_student_7420f5_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, verbose_name="Соревнование")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата")),
                ("result", models.CharField(blank=True, max_length=150, verbose_name="Результат")),
                ("has_certificate", models.BooleanField(default=False, verbose_name="Сертификат есть")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соревнование",
                "verbose_name_plural": "Соревнования",
                "ordering": ("-date", "-id"),
                "indexes": [models.Index(fields=["student", "-date"], name="students_co_student_c21a9e_idx")],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("olympiad", "Олимпиада"),
                            ("project", "Проект"),
                            ("research", "Исследование"),
                            ("startup", "Стартап"),
                            ("leadership", "Лидерство"),
                            ("volunteering", "Волонтёрство"),
                            ("competition", "Конкурс"),
                            ("award", "Награда"),
                        ],
                        max_length=16,
                        verbose_name="Категория",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("proof_url", models.URLField(blank=True, verbose_name="Подтверждение")),
                ("is_confirmed", models.BooleanField(default=False, verbose_name="Подтверждено")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Активность",
                "verbose_name_plural": "Активности",
                "ordering": ("-date", "-id"),
                "indexes": [models.Index(fields=["student", "category"], name="students_ac_student_c83863_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["grade"], name="students_st_grade_39b9da_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["graduation_year"], name="students_st_graduat_e520fc_idx"),
        ),
    ]
