# Generated by Django 5.1.5 on 2026-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_stable_student_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="source",
            field=models.CharField(
                choices=[("manual", "Внесён руками"), ("import", "Импорт"), ("platform", "Пройден на платформе")],
                default="manual",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
    ]
