# Generated by Django 5.1.5 on 2026-08-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_examattempt_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="activity",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="admissionprofile",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="admissionprofile",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="behaviorprofile",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="behaviorprofile",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="competition",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="competition",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="examprofile",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="examprofile",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="sportprofile",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="sportprofile",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="student",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="student",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="talentprofile",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
    ]
