# Generated by Django 5.1.5 on 2026-08-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionprofile",
            name="has_application_account",
            field=models.BooleanField(default=False, verbose_name="Кабинет подачи заведён"),
        ),
        migrations.AlterField(
            model_name="talentprofile",
            name="main_track",
            field=models.CharField(
                blank=True,
                choices=[
                    ("olympiad", "Олимпиады"),
                    ("research", "Исследования"),
                    ("startup", "Стартап"),
                    ("leadership", "Лидерство"),
                    ("volunteering", "Волонтёрство"),
                    ("competition", "Конкурсы"),
                ],
                max_length=32,
                verbose_name="Основной трек",
            ),
        ),
    ]
