# Generated by Django 5.1.5 on 2026-08-24 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_phase18_directories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="in_olympiad_group",
            field=models.BooleanField(default=False, verbose_name="В олимпиадной группе"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["in_olympiad_group"], name="students_st_in_olym_8ef66f_idx"),
        ),
    ]
