# Generated by Django 5.1.5 on 2026-08-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_phase19_materials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Внесён руками"),
                    ("import", "Импорт"),
                    ("platform", "Пройден на платформе"),
                    ("ai", "Распознано со скриншота"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
    ]
