# Generated by Django 5.1.5 on 2026-08-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_phase20_llm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("mother", "Мама"),
                            ("father", "Папа"),
                            ("guardian", "Опекун"),
                            ("grandparent", "Бабушка или дедушка"),
                            ("relative", "Другой родственник"),
                            ("other", "Другое"),
                        ],
                        max_length=16,
                        verbose_name="Кем приходится",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="Телефон")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Почта")),
                (
                    "preferred_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phone", "Звонок"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Почта"),
                        ],
                        max_length=16,
                        verbose_name="Предпочтительный способ связи",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Примечание")),
                ("is_primary", models.BooleanField(default=False, verbose_name="Основной контакт")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт родителя",
                "verbose_name_plural": "Контакты родителей",
                "ordering": ("-is_primary", "full_name", "id"),
                "indexes": [models.Index(fields=["student", "-is_primary"], name="students_pa_student_cd89b0_idx")],
            },
        ),
    ]
