# Generated by Django 5.1.5 on 2026-08-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directories", "0001_phase18_directories"),
        ("students", "0009_phase30_parent_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("school", "Школьный"),
                    ("city", "Городской"),
                    ("regional", "Областной"),
                    ("national", "Республиканский"),
                    ("international", "Международный"),
                ],
                max_length=16,
                verbose_name="Уровень",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="proof_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на подтверждение"),
        ),
        migrations.AddField(
            model_name="competition",
            name="sport_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="competitions",
                to="directories.sporttype",
                verbose_name="Вид спорта",
            ),
        ),
    ]
