# Generated by Django 5.1.5 on 2026-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_phase31_competitions_and_staff_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionprofile",
            name="cost_priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scholarship", "Нужна стипендия или грант"),
                    ("moderate", "Готовы платить умеренно"),
                    ("any", "Стоимость не главное"),
                    ("unknown", "Ещё не обсуждали"),
                ],
                max_length=16,
                verbose_name="Приоритет стоимости",
            ),
        ),
    ]
