# Generated by Django 5.1.5 on 2026-08-31 07:11

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_phase37_cost_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionprofile",
            name="target_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("foundation", "Foundation / подготовительный"),
                    ("bachelor", "Бакалавриат"),
                    ("master", "Магистратура"),
                ],
                max_length=16,
                verbose_name="Уровень цели",
            ),
        ),
        migrations.AddField(
            model_name="admissionprofile",
            name="target_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Год поступления"),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="exam_type",
            field=models.CharField(
                choices=[("IELTS", "IELTS"), ("TOEFL", "TOEFL"), ("SAT", "SAT"), ("ACT", "ACT"), ("ENT", "ЕНТ")],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("attestat", "Аттестат"),
                            ("transcript", "Транскрипт"),
                            ("exam_certificate", "Сертификат экзамена"),
                            ("recommendation", "Рекомендательное письмо"),
                            ("passport", "Паспорт"),
                            ("other", "Прочее"),
                        ],
                        max_length=24,
                        verbose_name="Тип документа",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Название")),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        storage=students.models._document_storage,
                        upload_to=students.models.document_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=64, verbose_name="Тип содержимого")),
                ("size", models.PositiveIntegerField(default=0, verbose_name="Размер, байт")),
                ("issued_date", models.DateField(blank=True, null=True, verbose_name="Дата выдачи")),
                ("expires_at", models.DateField(blank=True, null=True, verbose_name="Действует до")),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Загружен")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ ученика",
                "verbose_name_plural": "Документы учеников",
                "ordering": ("doc_type", "-created_at"),
                "indexes": [models.Index(fields=["student", "doc_type"], name="students_st_student_755288_idx")],
            },
        ),
    ]
