# Generated by Django 5.1.5 on 2026-08-31 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directories", "0002_phase39_exam_kinds"),
        ("students", "0012_phase38_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                (
                    "target_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True, verbose_name="Целевой балл"
                    ),
                ),
                ("exam_date", models.DateField(blank=True, null=True, verbose_name="Дата экзамена")),
                ("registration_date", models.DateField(blank=True, null=True, verbose_name="Дата регистрации")),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goals",
                        to="directories.examkind",
                        verbose_name="Экзамен",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_goals",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель по экзамену",
                "verbose_name_plural": "Цели по экзаменам",
                "ordering": ("exam_date", "exam__sort_order", "id"),
                "indexes": [models.Index(fields=["exam_date"], name="students_ex_exam_da_d0b3d7_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("archived_at__isnull", True)),
                        fields=("student", "exam"),
                        name="unique_active_exam_goal",
                    )
                ],
            },
        ),
    ]
