# Generated by Django 5.1.5 on 2026-08-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_phase39_exam_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("ENT", "ЕНТ"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
    ]
