"""Фаза 64: признак вымышленного ученика.

Ставится явно посевом или командой `mark_fictional`, а не выводится из
почты: по нему `preflight` ищет остатки, `purge_fictional` вычищает.
Данные миграция не трогает — у всех существующих признак снят.
"""

# Generated by Django 5.1.15 on 2026-09-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_phase63"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_fictional",
            field=models.BooleanField(default=False, verbose_name="Вымышленный"),
        ),
    ]
