# Generated by Django 5.2.17 on 2026-09-09 11:08

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0019_phase64"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionprofile",
            name="common_app_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Почта Common App"),
        ),
        migrations.AddField(
            model_name="admissionprofile",
            name="drive_folder_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Папка на Диске"),
        ),
        migrations.AddField(
            model_name="admissionprofile",
            name="student_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон ученика"),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="date_unknown",
            field=models.BooleanField(default=False, verbose_name="Дата не указана"),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="external_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="Внешняя ссылка"),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Внесён руками"),
                    ("import", "Импорт"),
                    ("admission_import", "Импорт Асем"),
                    ("platform", "Пройден на платформе"),
                    ("ai", "Распознано со скриншота"),
                ],
                default="manual",
                max_length=16,
                verbose_name="Источник",
            ),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                storage=students.models._document_storage,
                upload_to=students.models.document_upload_to,
                verbose_name="Файл",
            ),
        ),
        migrations.CreateModel(
            name="AdmissionImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                ("file_name", models.CharField(blank=True, max_length=250, verbose_name="Имя файла")),
                ("sheets", models.PositiveSmallIntegerField(default=0, verbose_name="Листов")),
                ("students_updated", models.PositiveIntegerField(default=0, verbose_name="Учеников обновлено")),
                ("attempts_created", models.PositiveIntegerField(default=0, verbose_name="Попыток создано")),
                ("documents_created", models.PositiveIntegerField(default=0, verbose_name="Документов-ссылок")),
                ("credentials_saved", models.PositiveIntegerField(default=0, verbose_name="Паролей записано")),
                ("rows_skipped", models.PositiveIntegerField(default=0, verbose_name="Строк пропущено")),
                ("report", models.TextField(blank=True, verbose_name="Отчёт")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Загрузка таблицы поступления",
                "verbose_name_plural": "Загрузки таблицы поступления",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="StudentCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("email", "Пароль от почты"), ("common_app", "Пароль Common App")],
                        max_length=16,
                        verbose_name="Что за пароль",
                    ),
                ),
                ("ciphertext", models.TextField(verbose_name="Шифртекст")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто записал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пароль ученика",
                "verbose_name_plural": "Пароли учеников",
                "constraints": [models.UniqueConstraint(fields=("student", "kind"), name="unique_student_credential")],
            },
        ),
    ]
