# Generated by Django 5.2.17 on 2026-09-09 17:26

import django.db.models.deletion
from django.conf import settings
import re

from django.db import migrations, models


def set_language_from_code(apps, schema_editor):
    """Язык группы — из её кода: «қаз 11 А» → каз, «рус 11 В» → рус.

    Не разобралось — русский: это язык, на котором школа говорит по
    умолчанию, и ошибиться им безопаснее, чем угадать неверно. Правит
    администратор, поэтому вечной эта догадка не будет.

    Пишем через `update()`, а не `save()`: сигналы аудита оставили бы
    в журнале правки без автора.
    """
    StudyGroup = apps.get_model("students", "StudyGroup")
    kk = re.compile(r"(қаз|каз|kaz|qaz)", re.IGNORECASE)
    ru = re.compile(r"(рус|rus)", re.IGNORECASE)
    for group in StudyGroup.objects.all():
        code = group.code or ""
        if kk.search(code):
            language = "kk"
        elif ru.search(code):
            language = "ru"
        else:
            language = "ru"
        StudyGroup.objects.filter(pk=group.pk).update(language=language)


def back(apps, schema_editor):
    """Обратно ничего делать не надо: поле уходит вместе со значением."""


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_phase65"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("kk", "Казахский")], default="ru", max_length=2, verbose_name="Язык группы"
            ),
        ),
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата")),
                ("present", models.BooleanField(default=True, verbose_name="Присутствовал")),
                ("reason", models.CharField(blank=True, max_length=200, verbose_name="Причина")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Отмечен")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменён")),
                (
                    "noted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_marks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отметил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "День посещаемости",
                "verbose_name_plural": "Дни посещаемости",
                "ordering": ("-date",),
                "indexes": [models.Index(fields=["student", "-date"], name="students_at_student_97696b_idx")],
                "constraints": [models.UniqueConstraint(fields=("student", "date"), name="unique_attendance_day")],
            },
        ),
        migrations.CreateModel(
            name="BehaviorRemark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("text", models.CharField(max_length=500, verbose_name="Замечание")),
                ("author_role", models.CharField(blank=True, max_length=32, verbose_name="Роль автора")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Записано")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behavior_remarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто записал",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замечание",
                "verbose_name_plural": "Замечания",
                "ordering": ("-date", "-created_at"),
                "indexes": [models.Index(fields=["student", "-date"], name="students_be_student_f9ddd8_idx")],
            },
        ),
        migrations.RunPython(set_language_from_code, back),
    ]
