# Generated by Django 5.2.17 on 2026-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0021_phase66"),
    ]

    operations = [
        migrations.AddField(
            model_name="behaviorremark",
            name="author_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Автор на момент удаления"),
        ),
        migrations.AddField(
            model_name="curatornote",
            name="author_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Автор на момент удаления"),
        ),
        migrations.AddField(
            model_name="mockimport",
            name="uploaded_by_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Кто загрузил, на момент удаления"),
        ),
    ]
