# Generated by Django 5.2.17 on 2026-09-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0022_phase67"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionprofile",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="admissionprofile",
            name="target_year",
        ),
    ]
