# Generated by Django 5.2.17 on 2026-09-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0023_phase68"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admissionprofile",
            name="cost_priority",
        ),
    ]
