# Generated by Django 5.2.17 on 2026-09-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0024_phase70_admission_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionimport",
            name="domains",
            field=models.CharField(blank=True, max_length=120, verbose_name="Домены"),
        ),
        migrations.AddField(
            model_name="admissionprofile",
            name="passport_expires_at",
            field=models.DateField(blank=True, null=True, verbose_name="Срок годности паспорта"),
        ),
        migrations.AddField(
            model_name="admissionprofile",
            name="personal_email",
            field=models.CharField(blank=True, max_length=254, verbose_name="Электронный адрес"),
        ),
    ]
