# Generated by Django 5.2.17 on 2026-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0025_phase71_import_registry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ждёт проверки"),
                    ("confirmed", "Подтверждён"),
                    ("rejected", "Отклонён"),
                    ("superseded", "Заменён документом куратора"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Проверка",
            ),
        ),
    ]
