# Generated by Django 5.2.17 on 2026-09-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0026_document_superseded_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="show_in_card",
            field=models.BooleanField(default=False, verbose_name="Показывать в карточке ученика"),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.PositiveSmallIntegerField(default=11, verbose_name="Класс"),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="grade",
            field=models.PositiveSmallIntegerField(default=11, verbose_name="Класс"),
        ),
    ]
