# Generated by Django 5.2.17 on 2026-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0029_parallel_of_group_and_year_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="home_room",
            field=models.CharField(blank=True, max_length=40, verbose_name="Домашний кабинет"),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="letter",
            field=models.CharField(blank=True, max_length=4, verbose_name="Литера"),
        ),
    ]
