# Generated by Django 5.2.17 on 2026-09-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0030_group_letter_and_home_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="behaviorprofile",
            name="homework_percent",
        ),
    ]
