# Generated by Django 5.2.17 on 2026-09-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0031_computed_homework_completion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mockimport",
            options={
                "ordering": ("-date", "-created_at"),
                "verbose_name": "Загрузка Mock Test",
                "verbose_name_plural": "Загрузки Mock Test",
            },
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="attempt_format",
            field=models.CharField(
                choices=[("mock", "Mock Test"), ("official", "Официальный")], max_length=8, verbose_name="Формат"
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="mock_import",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="students.mockimport",
                verbose_name="Загрузка Mock Test",
            ),
        ),
        migrations.AlterField(
            model_name="examprofile",
            name="next_mock_date",
            field=models.DateField(blank=True, null=True, verbose_name="Следующий Mock Test"),
        ),
        migrations.AlterField(
            model_name="mockimport",
            name="date",
            field=models.DateField(verbose_name="Дата Mock Test"),
        ),
    ]
