# Generated by Django 5.2.17 on 2026-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0032_mock_test_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionimport",
            name="uploaded_by_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Кто загрузил, на момент удаления"),
        ),
    ]
