# Generated by Django 5.1.5 on 2026-08-21 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, verbose_name="Специальность")),
                (
                    "level",
                    models.CharField(
                        choices=[("bachelor", "Бакалавриат"), ("master", "Магистратура"), ("foundation", "Foundation")],
                        default="bachelor",
                        max_length=16,
                        verbose_name="Уровень",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "Программа",
                "verbose_name_plural": "Программы",
                "ordering": ("university__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="AdmissionRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("ED", "Early Decision"),
                            ("EA", "Early Action"),
                            ("RD", "Regular Decision"),
                            ("Rolling", "Rolling"),
                        ],
                        max_length=8,
                        verbose_name="Тип раунда",
                    ),
                ),
                ("deadline", models.DateField(verbose_name="Дедлайн")),
                ("source_url", models.URLField(blank=True, verbose_name="Источник")),
                ("checked_at", models.DateTimeField(blank=True, null=True, verbose_name="Последняя сверка")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раунд подачи",
                "verbose_name_plural": "Раунды подачи",
                "ordering": ("deadline",),
            },
        ),
        migrations.CreateModel(
            name="StudentUniversity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tier",
                    models.CharField(
                        choices=[("reach", "Reach"), ("target", "Target"), ("safety", "Safety")],
                        default="target",
                        max_length=8,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начата"),
                            ("in_progress", "В работе"),
                            ("ready", "Готова"),
                            ("submitted", "Подана"),
                            ("accepted", "Принят"),
                            ("rejected", "Отказ"),
                            ("waitlist", "Лист ожидания"),
                        ],
                        default="not_started",
                        max_length=16,
                        verbose_name="Статус заявки",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="Примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                (
                    "admission_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicants",
                        to="universities.admissionround",
                        verbose_name="Раунд",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicants",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="universities",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вуз ученика",
                "verbose_name_plural": "Вузы учеников",
                "ordering": ("student", "tier"),
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="Название")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("website", models.URLField(blank=True, verbose_name="Сайт")),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="Например utoronto.ca — по нему сверяются источники",
                        max_length=100,
                        verbose_name="Домен для сверки",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Вуз",
                "verbose_name_plural": "Вузы",
                "ordering": ("name",),
                "indexes": [models.Index(fields=["country"], name="universitie_country_a1a531_idx")],
            },
        ),
        migrations.AddField(
            model_name="program",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="universities.university",
                verbose_name="Вуз",
            ),
        ),
        migrations.AddIndex(
            model_name="admissionround",
            index=models.Index(fields=["deadline"], name="universitie_deadlin_c95c74_idx"),
        ),
        migrations.AddConstraint(
            model_name="admissionround",
            constraint=models.UniqueConstraint(fields=("program", "round_type"), name="uniq_round_per_program"),
        ),
        migrations.AddConstraint(
            model_name="studentuniversity",
            constraint=models.UniqueConstraint(fields=("student", "program"), name="uniq_student_program"),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("university", "name", "level"), name="uniq_program_per_university"
            ),
        ),
    ]
