# Generated by Django 5.1.5 on 2026-08-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "min_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="Минимальный GPA"
                    ),
                ),
                (
                    "min_ielts",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="Минимальный IELTS"
                    ),
                ),
                (
                    "min_toefl",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Минимальный TOEFL"),
                ),
                ("min_sat", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Минимальный SAT")),
                ("min_act", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Минимальный ACT")),
                (
                    "required_subjects",
                    models.CharField(
                        blank=True, help_text="Через запятую", max_length=300, verbose_name="Требуемые предметы"
                    ),
                ),
                ("portfolio_required", models.BooleanField(default=False, verbose_name="Нужно портфолио")),
                ("portfolio_note", models.CharField(blank=True, max_length=300, verbose_name="Требования к портфолио")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                ("source_url", models.URLField(blank=True, verbose_name="Источник")),
                ("checked_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата актуализации")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Требования программы",
                "verbose_name_plural": "Требования программ",
                "ordering": ("program__university__name", "program__name"),
            },
        ),
    ]
