# Generated by Django 5.1.5 on 2026-08-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_admissionrequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentuniversity",
            name="added_by",
            field=models.CharField(
                choices=[("director", "Директор по поступлению"), ("student", "Ученик"), ("import", "Импорт")],
                default="director",
                max_length=16,
                verbose_name="Кто добавил",
            ),
        ),
        migrations.AddField(
            model_name="studentuniversity",
            name="is_confirmed",
            field=models.BooleanField(default=True, verbose_name="Подтверждено директором"),
        ),
    ]
