# Generated by Django 5.1.5 on 2026-08-22 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0003_student_adds_programs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admissionrequirement",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("school", "Заведено школой"),
                    ("seed", "Стартовый справочник"),
                    ("import", "Импорт файла"),
                    ("sync", "Фоновая сверка"),
                ],
                default="school",
                max_length=16,
                verbose_name="Источник записи",
            ),
        ),
        migrations.AddField(
            model_name="admissionrequirement",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Данные подтверждены"),
        ),
        migrations.AddField(
            model_name="admissionrequirement",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда подтверждено"),
        ),
        migrations.AddField(
            model_name="admissionrequirement",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто подтвердил",
            ),
        ),
        migrations.AddField(
            model_name="admissionround",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("school", "Заведено школой"),
                    ("seed", "Стартовый справочник"),
                    ("import", "Импорт файла"),
                    ("sync", "Фоновая сверка"),
                ],
                default="school",
                max_length=16,
                verbose_name="Источник записи",
            ),
        ),
        migrations.AddField(
            model_name="admissionround",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Данные подтверждены"),
        ),
        migrations.AddField(
            model_name="admissionround",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда подтверждено"),
        ),
        migrations.AddField(
            model_name="admissionround",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто подтвердил",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("school", "Заведено школой"),
                    ("seed", "Стартовый справочник"),
                    ("import", "Импорт файла"),
                    ("sync", "Фоновая сверка"),
                ],
                default="school",
                max_length=16,
                verbose_name="Источник записи",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Данные подтверждены"),
        ),
        migrations.AddField(
            model_name="program",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда подтверждено"),
        ),
        migrations.AddField(
            model_name="program",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто подтвердил",
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("school", "Заведено школой"),
                    ("seed", "Стартовый справочник"),
                    ("import", "Импорт файла"),
                    ("sync", "Фоновая сверка"),
                ],
                default="school",
                max_length=16,
                verbose_name="Источник записи",
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Данные подтверждены"),
        ),
        migrations.AddField(
            model_name="university",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда подтверждено"),
        ),
        migrations.AddField(
            model_name="university",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто подтвердил",
            ),
        ),
    ]
