# Generated by Django 5.1.5 on 2026-08-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0004_catalog_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentuniversity",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="studentuniversity",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с"),
        ),
    ]
