# Generated by Django 5.1.5 on 2026-08-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_soft_delete"),
        ("universities", "0005_soft_delete"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studentuniversity",
            name="uniq_student_program",
        ),
        migrations.AddConstraint(
            model_name="studentuniversity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("student", "program"),
                name="uniq_student_program",
            ),
        ),
    ]
