# Generated by Django 5.1.5 on 2026-08-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0006_unique_ignores_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionrequirement",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("school", "Заведено школой"),
                    ("seed", "Стартовый справочник"),
                    ("import", "Импорт файла"),
                    ("sync", "Фоновая сверка"),
                    ("ai", "Разобрано помощником"),
                ],
                default="school",
                max_length=16,
                verbose_name="Источник записи",
            ),
        ),
        migrations.AlterField(
            model_name="admissionround",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("school", "Заведено школой"),
                    ("seed", "Стартовый справочник"),
                    ("import", "Импорт файла"),
                    ("sync", "Фоновая сверка"),
                    ("ai", "Разобрано помощником"),
                ],
                default="school",
                max_length=16,
                verbose_name="Источник записи",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("school", "Заведено школой"),
                    ("seed", "Стартовый справочник"),
                    ("import", "Импорт файла"),
                    ("sync", "Фоновая сверка"),
                    ("ai", "Разобрано помощником"),
                ],
                default="school",
                max_length=16,
                verbose_name="Источник записи",
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("school", "Заведено школой"),
                    ("seed", "Стартовый справочник"),
                    ("import", "Импорт файла"),
                    ("sync", "Фоновая сверка"),
                    ("ai", "Разобрано помощником"),
                ],
                default="school",
                max_length=16,
                verbose_name="Источник записи",
            ),
        ),
    ]
