# Generated by Django 5.1.5 on 2026-08-31 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_phase39_exam_goals"),
        ("universities", "0007_phase20_llm"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="world_rank",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Место в мировом рейтинге"),
        ),
        migrations.CreateModel(
            name="MatchRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("major", models.CharField(blank=True, max_length=150, verbose_name="Специальность")),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[("bachelor", "Бакалавриат"), ("master", "Магистратура"), ("foundation", "Foundation")],
                        max_length=16,
                        verbose_name="Уровень",
                    ),
                ),
                ("countries", models.CharField(blank=True, max_length=500, verbose_name="Страны")),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Считается"), ("done", "Готов"), ("failed", "Не получился")],
                        default="running",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("stage", models.CharField(blank=True, max_length=24, verbose_name="Этап")),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="Прогресс, %")),
                ("error", models.CharField(blank=True, max_length=250, verbose_name="Что пошло не так")),
                (
                    "snapshot_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="GPA на момент"
                    ),
                ),
                (
                    "snapshot_ielts",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="IELTS на момент"
                    ),
                ),
                ("snapshot_sat", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="SAT на момент")),
                ("snapshot_grade", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Класс")),
                (
                    "snapshot_graduation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Год выпуска"),
                ),
                ("funnel_catalog", models.PositiveIntegerField(default=0, verbose_name="В каталоге")),
                ("funnel_filtered", models.PositiveIntegerField(default=0, verbose_name="Прошло фильтр")),
                ("funnel_analyzed", models.PositiveIntegerField(default=0, verbose_name="Разобрано подробно")),
                ("funnel_final", models.PositiveIntegerField(default=0, verbose_name="В финальном списке")),
                ("strategy_position", models.TextField(blank=True, verbose_name="Текущая позиция")),
                ("strategy_improve", models.TextField(blank=True, verbose_name="Что важно усилить")),
                ("strategy_next", models.TextField(blank=True, verbose_name="Следующий шаг")),
                ("strategy_offline", models.BooleanField(default=True, verbose_name="Собрана правилами")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Запущен")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Закончен")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_runs",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогон подбора",
                "verbose_name_plural": "Прогоны подбора",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MatchRunResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("percent_now", models.PositiveSmallIntegerField(default=0, verbose_name="Соответствие сейчас")),
                ("percent_goal", models.PositiveSmallIntegerField(default=0, verbose_name="Если закрыть разрывы")),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dream", "Dream — очень конкурентно, но стоит попробовать"),
                            ("reach", "Reach — амбициозно, нужны усилия"),
                            ("match", "Match — реалистично при текущей траектории"),
                            ("safety", "Safety — уже соответствуете или превышаете"),
                        ],
                        max_length=8,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("top", "Финальный список"),
                            ("strong", "Ещё сильные варианты"),
                            ("other", "Другие университеты"),
                        ],
                        default="other",
                        max_length=8,
                        verbose_name="Раздел",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_results",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="universities.matchrun",
                        verbose_name="Прогон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка результата подбора",
                "verbose_name_plural": "Строки результатов подбора",
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="FavoriteProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Отмечено")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранная программа",
                "verbose_name_plural": "Избранные программы",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(fields=("student", "program"), name="uniq_favorite_per_student")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="matchrun",
            index=models.Index(fields=["student", "-created_at"], name="universitie_student_d48767_idx"),
        ),
        migrations.AddConstraint(
            model_name="matchrunresult",
            constraint=models.UniqueConstraint(fields=("run", "program"), name="uniq_program_per_run"),
        ),
    ]
