# Generated by Django 5.1.5 on 2026-08-31 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_phase42_exam_types"),
        ("universities", "0008_phase40_selection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("school", "Заведено школой"),
                            ("seed", "Стартовый справочник"),
                            ("import", "Импорт файла"),
                            ("sync", "Фоновая сверка"),
                            ("ai", "Разобрано помощником"),
                        ],
                        default="school",
                        max_length=16,
                        verbose_name="Источник записи",
                    ),
                ),
                ("is_verified", models.BooleanField(default=True, verbose_name="Данные подтверждены")),
                ("verified_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда подтверждено")),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                ("organizer", models.CharField(blank=True, max_length=250, verbose_name="Организатор")),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="Страна")),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[("bachelor", "Бакалавриат"), ("master", "Магистратура"), ("foundation", "Foundation")],
                        max_length=16,
                        verbose_name="Уровень обучения",
                    ),
                ),
                (
                    "funding_type",
                    models.CharField(
                        choices=[
                            ("full", "Полное финансирование"),
                            ("partial", "Частичное финансирование"),
                            ("tuition", "Только обучение"),
                        ],
                        default="partial",
                        max_length=12,
                        verbose_name="Тип финансирования",
                    ),
                ),
                (
                    "amount_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Сумма от"
                    ),
                ),
                (
                    "amount_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Сумма до"
                    ),
                ),
                ("currency", models.CharField(blank=True, default="USD", max_length=8, verbose_name="Валюта")),
                ("for_international", models.BooleanField(default=False, verbose_name="Для иностранцев")),
                ("for_merit", models.BooleanField(default=False, verbose_name="За заслуги")),
                ("for_need", models.BooleanField(default=False, verbose_name="По нужде")),
                ("deadline", models.DateField(blank=True, null=True, verbose_name="Дедлайн подачи")),
                ("url", models.URLField(blank=True, verbose_name="Страница стипендии")),
                ("requirements", models.TextField(blank=True, verbose_name="Требования")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Заведена")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто — стипендия не привязана к вузу",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scholarships",
                        to="universities.university",
                        verbose_name="Вуз",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто подтвердил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стипендия",
                "verbose_name_plural": "Стипендии",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SavedScholarship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Сохранена")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_scholarships",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="universities.scholarship",
                        verbose_name="Стипендия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сохранённая стипендия",
                "verbose_name_plural": "Сохранённые стипендии",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="scholarship",
            index=models.Index(fields=["deadline"], name="universitie_deadlin_4aac5c_idx"),
        ),
        migrations.AddIndex(
            model_name="scholarship",
            index=models.Index(fields=["country"], name="universitie_country_73ea2d_idx"),
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.UniqueConstraint(fields=("name", "organizer"), name="uniq_scholarship_name"),
        ),
        migrations.AddConstraint(
            model_name="savedscholarship",
            constraint=models.UniqueConstraint(
                fields=("student", "scholarship"), name="uniq_saved_scholarship_per_student"
            ),
        ),
    ]
