# Generated by Django 5.2.17 on 2026-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0024_phase70_admission_card"),
        ("universities", "0009_phase44_scholarships"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentuniversity",
            options={
                "ordering": ("student", "-is_priority", "tier"),
                "verbose_name": "Вуз ученика",
                "verbose_name_plural": "Вузы учеников",
            },
        ),
        migrations.AddField(
            model_name="studentuniversity",
            name="is_priority",
            field=models.BooleanField(default=False, verbose_name="Приоритетный"),
        ),
        migrations.AddConstraint(
            model_name="studentuniversity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True), ("is_priority", True)),
                fields=("student",),
                name="uniq_student_priority",
            ),
        ),
    ]
