# Generated by Django 5.1.5 on 2026-08-22 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0003_examattempt_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MockExam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("IELTS", "IELTS"), ("TOEFL", "TOEFL"), ("SAT", "SAT"), ("ACT", "ACT")],
                        max_length=8,
                        verbose_name="Экзамен",
                    ),
                ),
                ("time_limit_minutes", models.PositiveSmallIntegerField(default=60, verbose_name="Ограничение, минут")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
            ],
            options={
                "verbose_name": "Пробный экзамен",
                "verbose_name_plural": "Пробные экзамены",
                "ordering": ("exam_type", "title"),
            },
        ),
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("IELTS", "IELTS"), ("TOEFL", "TOEFL"), ("SAT", "SAT"), ("ACT", "ACT")],
                        max_length=8,
                        verbose_name="Экзамен",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                            ("math", "Math"),
                            ("verbal", "Verbal"),
                            ("english", "English"),
                            ("science", "Science"),
                        ],
                        max_length=16,
                        verbose_name="Секция",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("easy", "Простое"), ("medium", "Среднее"), ("hard", "Сложное")],
                        max_length=8,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Идёт"), ("finished", "Завершена"), ("abandoned", "Брошена")],
                        default="running",
                        max_length=16,
                        verbose_name="Состояние",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Начата")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершена")),
                ("seconds_spent", models.PositiveIntegerField(default=0, verbose_name="Секунд потрачено")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="MockRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("counted_in_profile", models.BooleanField(default=False, verbose_name="Учтён в текущем балле")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда решено")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Начат")),
                (
                    "exam_attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mock_run",
                        to="students.examattempt",
                        verbose_name="Попытка экзамена",
                    ),
                ),
                (
                    "mock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="prep.mockexam",
                        verbose_name="Мок",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_mock_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто решил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_runs",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_run",
                        to="prep.practicesession",
                        verbose_name="Сессия ответов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прохождение мока",
                "verbose_name_plural": "Прохождения моков",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("IELTS", "IELTS"), ("TOEFL", "TOEFL"), ("SAT", "SAT"), ("ACT", "ACT")],
                        max_length=8,
                        verbose_name="Экзамен",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                            ("math", "Math"),
                            ("verbal", "Verbal"),
                            ("english", "English"),
                            ("science", "Science"),
                        ],
                        max_length=16,
                        verbose_name="Секция",
                    ),
                ),
                ("topic", models.CharField(db_index=True, max_length=120, verbose_name="Тема")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "Простое"), ("medium", "Среднее"), ("hard", "Сложное")],
                        default="medium",
                        max_length=8,
                        verbose_name="Сложность",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст задания")),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Показывается в разборе после ответа", verbose_name="Объяснение"
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=250, verbose_name="Источник")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Банк заданий",
                "ordering": ("exam_type", "section", "topic", "id"),
                "indexes": [
                    models.Index(fields=["exam_type", "section", "difficulty"], name="prep_questi_exam_ty_e52720_idx"),
                    models.Index(fields=["topic"], name="prep_questi_topic_fd373f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("letter", models.CharField(max_length=2, verbose_name="Метка")),
                ("text", models.CharField(max_length=500, verbose_name="Текст варианта")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Верный")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="prep.question",
                        verbose_name="Задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
                "ordering": ("question", "letter"),
            },
        ),
        migrations.CreateModel(
            name="PracticeAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Верно")),
                ("seconds", models.PositiveIntegerField(default=0, verbose_name="Секунд на ответ")),
                ("answered_at", models.DateTimeField(auto_now_add=True, verbose_name="Отвечено")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="prep.practicesession",
                        verbose_name="Тренировка",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="prep.question",
                        verbose_name="Задание",
                    ),
                ),
                (
                    "chosen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="prep.questionoption",
                        verbose_name="Выбранный вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
                "ordering": ("session", "id"),
            },
        ),
        migrations.CreateModel(
            name="MockSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                            ("math", "Math"),
                            ("verbal", "Verbal"),
                            ("english", "English"),
                            ("science", "Science"),
                        ],
                        max_length=16,
                        verbose_name="Секция",
                    ),
                ),
                ("question_count", models.PositiveSmallIntegerField(default=10, verbose_name="Сколько заданий")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
                (
                    "mock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="prep.mockexam",
                        verbose_name="Мок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Секция мока",
                "verbose_name_plural": "Секции мока",
                "ordering": ("mock", "order"),
                "constraints": [models.UniqueConstraint(fields=("mock", "section"), name="uniq_section_per_mock")],
            },
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(fields=["student", "-started_at"], name="prep_practi_student_3b8d21_idx"),
        ),
        migrations.AddIndex(
            model_name="mockrun",
            index=models.Index(fields=["student", "-created_at"], name="prep_mockru_student_ab508a_idx"),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(fields=("question", "letter"), name="uniq_option_letter"),
        ),
        migrations.AddConstraint(
            model_name="practiceanswer",
            constraint=models.UniqueConstraint(
                fields=("session", "question"), name="uniq_answer_per_question_in_session"
            ),
        ),
    ]
