# Generated by Django 5.1.5 on 2026-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prep", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockexam",
            name="exam_type",
            field=models.CharField(
                choices=[("IELTS", "IELTS"), ("TOEFL", "TOEFL"), ("SAT", "SAT"), ("ACT", "ACT"), ("ENT", "ЕНТ")],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="practicesession",
            name="exam_type",
            field=models.CharField(
                choices=[("IELTS", "IELTS"), ("TOEFL", "TOEFL"), ("SAT", "SAT"), ("ACT", "ACT"), ("ENT", "ЕНТ")],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam_type",
            field=models.CharField(
                choices=[("IELTS", "IELTS"), ("TOEFL", "TOEFL"), ("SAT", "SAT"), ("ACT", "ACT"), ("ENT", "ЕНТ")],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
    ]
