# Generated by Django 5.1.5 on 2026-08-31 10:58

import django.db.models.deletion
import prep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prep", "0002_phase38_ent_exam_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionPassage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("IELTS", "IELTS"),
                            ("TOEFL", "TOEFL"),
                            ("SAT", "SAT"),
                            ("ACT", "ACT"),
                            ("ENT", "ЕНТ"),
                            ("Duolingo", "Duolingo"),
                            ("HSK", "HSK"),
                        ],
                        max_length=12,
                        verbose_name="Экзамен",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                            ("math", "Math"),
                            ("verbal", "Verbal"),
                            ("english", "English"),
                            ("science", "Science"),
                        ],
                        max_length=16,
                        verbose_name="Секция",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("reading", "Текст для чтения"), ("listening", "Аудио для аудирования")],
                        max_length=12,
                        verbose_name="Вид источника",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Заголовок")),
                ("body", models.TextField(blank=True, verbose_name="Текст или расшифровка")),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        storage=prep.models._prep_storage,
                        upload_to=prep.models._passage_media_to,
                        verbose_name="Аудиофайл",
                    ),
                ),
                ("audio_content_type", models.CharField(blank=True, max_length=64, verbose_name="Тип аудио")),
                ("audio_start", models.PositiveIntegerField(blank=True, null=True, verbose_name="Начало отрезка, с")),
                ("audio_end", models.PositiveIntegerField(blank=True, null=True, verbose_name="Конец отрезка, с")),
                ("source", models.CharField(blank=True, max_length=250, verbose_name="Источник")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
            ],
            options={
                "verbose_name": "Источник для вопросов",
                "verbose_name_plural": "Источники для вопросов",
                "ordering": ("exam_type", "section", "id"),
            },
        ),
        migrations.AddField(
            model_name="mocksection",
            name="section_time_minutes",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Время на секцию, минут"),
        ),
        migrations.AddField(
            model_name="question",
            name="criteria",
            field=models.TextField(blank=True, verbose_name="Критерии оценивания"),
        ),
        migrations.AddField(
            model_name="question",
            name="expected_seconds",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Время на решение, с"),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.FileField(
                blank=True,
                max_length=300,
                storage=prep.models._prep_storage,
                upload_to="prep/questions/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=64, verbose_name="Тип изображения"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single", "Один верный вариант"),
                    ("multiple", "Несколько верных"),
                    ("short", "Короткий ответ"),
                    ("writing", "Письменное задание"),
                    ("speaking", "Устное задание"),
                ],
                default="single",
                max_length=12,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="sample_answer",
            field=models.TextField(blank=True, verbose_name="Образец ответа"),
        ),
        migrations.AddField(
            model_name="question",
            name="source_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Год источника"),
        ),
        migrations.AddField(
            model_name="question",
            name="subtopic",
            field=models.CharField(blank=True, max_length=120, verbose_name="Подтема"),
        ),
        migrations.AlterField(
            model_name="mockexam",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("ENT", "ЕНТ"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="practicesession",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("ENT", "ЕНТ"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("ENT", "ЕНТ"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=12,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="passage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="prep.questionpassage",
                verbose_name="Источник",
            ),
        ),
        migrations.CreateModel(
            name="TheoryLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("IELTS", "IELTS"),
                            ("TOEFL", "TOEFL"),
                            ("SAT", "SAT"),
                            ("ACT", "ACT"),
                            ("ENT", "ЕНТ"),
                            ("Duolingo", "Duolingo"),
                            ("HSK", "HSK"),
                        ],
                        max_length=12,
                        verbose_name="Экзамен",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                            ("math", "Math"),
                            ("verbal", "Verbal"),
                            ("english", "English"),
                            ("science", "Science"),
                        ],
                        max_length=16,
                        verbose_name="Секция",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "level",
                    models.CharField(
                        choices=[("basic", "Базовый"), ("medium", "Средний"), ("advanced", "Продвинутый")],
                        default="basic",
                        max_length=12,
                        verbose_name="Уровень",
                    ),
                ),
                ("reading_minutes", models.PositiveSmallIntegerField(default=5, verbose_name="Время чтения, минут")),
                ("body", models.TextField(blank=True, verbose_name="Текст урока")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        storage=prep.models._prep_storage,
                        upload_to="prep/theory/",
                        verbose_name="Файл",
                    ),
                ),
                ("file_content_type", models.CharField(blank=True, max_length=64, verbose_name="Тип файла")),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
            ],
            options={
                "verbose_name": "Урок теории",
                "verbose_name_plural": "Теория",
                "ordering": ("exam_type", "section", "order", "id"),
                "indexes": [models.Index(fields=["exam_type", "section"], name="prep_theory_exam_ty_b02d9c_idx")],
            },
        ),
    ]
