# Generated by Django 5.1.5 on 2026-08-31 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prep", "0003_phase42_bank_format"),
        ("students", "0014_phase42_exam_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("solo", "Соло на время"), ("duel", "Вызов однокласснику")],
                        default="solo",
                        max_length=8,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("IELTS", "IELTS"),
                            ("TOEFL", "TOEFL"),
                            ("SAT", "SAT"),
                            ("ACT", "ACT"),
                            ("ENT", "ЕНТ"),
                            ("Duolingo", "Duolingo"),
                            ("HSK", "HSK"),
                        ],
                        max_length=12,
                        verbose_name="Экзамен",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("speaking", "Speaking"),
                            ("math", "Math"),
                            ("verbal", "Verbal"),
                            ("english", "English"),
                            ("science", "Science"),
                        ],
                        max_length=16,
                        verbose_name="Секция",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "Ждёт соперника"), ("running", "Идёт"), ("done", "Закончен")],
                        default="running",
                        max_length=8,
                        verbose_name="Состояние",
                    ),
                ),
                ("code", models.CharField(blank=True, db_index=True, max_length=8, verbose_name="Код вызова")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Начат")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Закончен")),
            ],
            options={
                "verbose_name": "Матч квиза",
                "verbose_name_plural": "Матчи квиза",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="QuizPlayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveIntegerField(default=0, verbose_name="Счёт")),
                ("correct", models.PositiveSmallIntegerField(default=0, verbose_name="Верных ответов")),
                ("total", models.PositiveSmallIntegerField(default=0, verbose_name="Всего заданий")),
                ("seconds", models.PositiveIntegerField(default=0, verbose_name="Секунд")),
                ("best_streak", models.PositiveSmallIntegerField(default=0, verbose_name="Лучшая серия")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Закончил")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="prep.quizmatch",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_player",
                        to="prep.practicesession",
                        verbose_name="Сессия",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_players",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник матча",
                "verbose_name_plural": "Участники матчей",
                "ordering": ("-score", "seconds"),
                "indexes": [models.Index(fields=["student", "-id"], name="prep_quizpl_student_5c8947_idx")],
                "constraints": [models.UniqueConstraint(fields=("match", "student"), name="uniq_player_per_match")],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="prep.quizmatch",
                        verbose_name="Матч",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_rows",
                        to="prep.question",
                        verbose_name="Задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание матча",
                "verbose_name_plural": "Задания матча",
                "ordering": ("order", "id"),
                "constraints": [models.UniqueConstraint(fields=("match", "question"), name="uniq_question_per_match")],
            },
        ),
    ]
