# Generated by Django 5.1.15 on 2026-09-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prep", "0004_phase46_quiz_and_badges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockexam",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="practicesession",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=8,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=12,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="questionpassage",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=12,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="quizmatch",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=12,
                verbose_name="Экзамен",
            ),
        ),
        migrations.AlterField(
            model_name="theorylesson",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFL"),
                    ("SAT", "SAT"),
                    ("ACT", "ACT"),
                    ("Duolingo", "Duolingo"),
                    ("HSK", "HSK"),
                ],
                max_length=12,
                verbose_name="Экзамен",
            ),
        ),
    ]
