# Generated by Django 5.2.17 on 2026-09-20 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prep", "0005_phase59"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="practiceanswer",
            name="review_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий проверяющего"),
        ),
        migrations.AddField(
            model_name="practiceanswer",
            name="review_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True, verbose_name="Оценка проверяющего"
            ),
        ),
        migrations.AddField(
            model_name="practiceanswer",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Проверено"),
        ),
        migrations.AddField(
            model_name="practiceanswer",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_open_answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Проверил",
            ),
        ),
        migrations.AddField(
            model_name="practiceanswer",
            name="text",
            field=models.TextField(blank=True, verbose_name="Открытый ответ"),
        ),
        migrations.AddField(
            model_name="question",
            name="minute_limit",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Лимит минут"),
        ),
        migrations.AddField(
            model_name="question",
            name="word_limit",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Лимит слов"),
        ),
    ]
