# Generated by Django 5.2.17 on 2026-09-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prep", "0006_bank_open_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestion",
            name="match",
        ),
        migrations.RemoveField(
            model_name="quizplayer",
            name="match",
        ),
        migrations.RemoveField(
            model_name="quizplayer",
            name="session",
        ),
        migrations.RemoveField(
            model_name="quizplayer",
            name="student",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="question",
        ),
        migrations.DeleteModel(
            name="QuizMatch",
        ),
        migrations.DeleteModel(
            name="QuizPlayer",
        ),
        migrations.DeleteModel(
            name="QuizQuestion",
        ),
    ]
