# Generated by Django 5.2.17 on 2026-09-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prep", "0007_drop_quiz"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mockexam",
            options={
                "ordering": ("exam_type", "title"),
                "verbose_name": "Mock Test онлайн",
                "verbose_name_plural": "Mock Test онлайн",
            },
        ),
        migrations.AlterModelOptions(
            name="mockrun",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Прохождение Mock Test",
                "verbose_name_plural": "Прохождения Mock Test",
            },
        ),
        migrations.AlterModelOptions(
            name="mocksection",
            options={
                "ordering": ("mock", "order"),
                "verbose_name": "Секция Mock Test",
                "verbose_name_plural": "Секции Mock Test",
            },
        ),
        migrations.AlterField(
            model_name="mockrun",
            name="mock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="prep.mockexam",
                verbose_name="Mock Test",
            ),
        ),
        migrations.AlterField(
            model_name="mocksection",
            name="mock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="prep.mockexam",
                verbose_name="Mock Test",
            ),
        ),
    ]
