# Generated by Django 5.2.17 on 2026-09-30 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0005_school_report_templates"),
        ("students", "0030_group_letter_and_home_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("requires_submission", models.BooleanField(default=False, verbose_name="Нужна сдача в LMS")),
                ("due_at", models.DateTimeField(blank=True, null=True, verbose_name="Срок сдачи")),
                (
                    "late_policy",
                    models.CharField(
                        choices=[("accept", "Принимать с пометкой «с опозданием»"), ("close", "Закрыть сдачу")],
                        default="accept",
                        max_length=8,
                        verbose_name="После срока",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Задано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменено")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто задал",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="academics.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание со сдачей",
                "verbose_name_plural": "Задания со сдачей",
                "ordering": ("-due_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст ответа")),
                ("link", models.URLField(blank=True, max_length=500, verbose_name="Ссылка")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий учителю")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="Сдано")),
                ("late_minutes", models.PositiveIntegerField(blank=True, null=True, verbose_name="Опоздание, мин")),
                ("checked_at", models.DateTimeField(blank=True, null=True, verbose_name="Проверено")),
                ("grade", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Оценка")),
                ("teacher_comment", models.TextField(blank=True, verbose_name="Комментарий учителя")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменено")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="homework.assignment",
                        verbose_name="Задание",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто проверил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сдача ДЗ",
                "verbose_name_plural": "Сдачи ДЗ",
                "ordering": ("assignment", "student"),
            },
        ),
        migrations.CreateModel(
            name="HomeworkFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("key", models.CharField(max_length=300, unique=True, verbose_name="Ключ в хранилище")),
                ("name", models.CharField(max_length=250, verbose_name="Имя файла")),
                ("content_type", models.CharField(blank=True, max_length=120, verbose_name="Тип")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("image", "Фото"),
                            ("audio", "Аудио"),
                            ("video", "Видео"),
                            ("other", "Файл"),
                        ],
                        default="other",
                        max_length=8,
                        verbose_name="Вид",
                    ),
                ),
                ("size", models.BigIntegerField(default=0, verbose_name="Размер, байт")),
                ("photos", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Из фото")),
                (
                    "state",
                    models.CharField(
                        choices=[("uploading", "Загружается"), ("ready", "Загружен")],
                        default="uploading",
                        max_length=10,
                        verbose_name="Состояние",
                    ),
                ),
                ("upload_id", models.CharField(blank=True, max_length=200, verbose_name="Загрузка по частям")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Загружен")),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="homework.assignment",
                        verbose_name="Задание",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто загрузил",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="homework.submission",
                        verbose_name="Сдача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл ДЗ",
                "verbose_name_plural": "Файлы ДЗ",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["requires_submission", "due_at"], name="homework_as_require_24e8b8_idx"),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)), fields=("lesson",), name="one_assignment_per_lesson"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["student", "submitted_at"], name="homework_su_student_faa549_idx"),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("assignment", "student"),
                name="one_submission_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("grade__isnull", True), models.Q(("grade__gte", 1), ("grade__lte", 10)), _connector="OR"
                ),
                name="homework_grade_1_10",
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworkfile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("assignment__isnull", False), ("submission__isnull", True)),
                    models.Q(("assignment__isnull", True), ("submission__isnull", False)),
                    _connector="OR",
                ),
                name="homework_file_has_one_owner",
            ),
        ),
    ]
