# Generated by Django 5.2.17 on 2026-09-26 17:52

import academics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0027_competition_in_card_and_school_grade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=32, unique=True, verbose_name="Код")),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("short_title", models.CharField(max_length=32, verbose_name="Короткое название")),
                (
                    "scheme",
                    models.CharField(
                        choices=[("kz", "ФО, СОР и СОЧ, итог за четверть"), ("fo", "Только ФО, в табель не идёт")],
                        default="kz",
                        max_length=2,
                        verbose_name="Схема оценивания",
                    ),
                ),
                ("sor_max", models.PositiveSmallIntegerField(default=15, verbose_name="Максимум СОР по умолчанию")),
                ("soch_max", models.PositiveSmallIntegerField(default=25, verbose_name="Максимум СОЧ по умолчанию")),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ведётся")),
                ("is_fictional", models.BooleanField(default=False, verbose_name="Вымышленный")),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ("order", "title"),
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=20, verbose_name="Название")),
                ("starts", models.DateField(verbose_name="Начало")),
                ("ends", models.DateField(verbose_name="Конец")),
                ("is_current", models.BooleanField(default=False, verbose_name="Текущий")),
                ("is_fictional", models.BooleanField(default=False, verbose_name="Вымышленный")),
            ],
            options={
                "verbose_name": "Учебный год",
                "verbose_name_plural": "Учебные годы",
                "ordering": ("-starts",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)), fields=("is_current",), name="one_current_year"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Break",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=60, verbose_name="Название")),
                ("starts", models.DateField(verbose_name="Начало")),
                ("ends", models.DateField(verbose_name="Конец")),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaks",
                        to="academics.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Каникулы",
                "verbose_name_plural": "Каникулы",
                "ordering": ("starts",),
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("group", "Вся группа"), ("subgroup", "Подгруппа"), ("stream", "Поток")],
                        max_length=8,
                        verbose_name="Вид",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Номер подгруппы")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("short_name", models.CharField(blank=True, max_length=60, verbose_name="Короткое название")),
                ("rule", models.CharField(blank=True, max_length=60, verbose_name="Как делили")),
                ("is_fictional", models.BooleanField(default=False, verbose_name="Вымышленный")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="students.studygroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subgroups",
                        to="academics.subject",
                        verbose_name="Предмет подгруппы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав",
                "verbose_name_plural": "Составы",
                "ordering": ("kind", "name"),
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="academics.cohort",
                        verbose_name="Состав",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учитель",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="academics.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал",
                "verbose_name_plural": "Журналы",
                "ordering": ("subject__order", "cohort__name"),
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weight_fo", models.PositiveSmallIntegerField(default=25, verbose_name="Вес ФО, %")),
                ("weight_sor", models.PositiveSmallIntegerField(default=25, verbose_name="Вес СОР, %")),
                ("weight_soch", models.PositiveSmallIntegerField(default=50, verbose_name="Вес СОЧ, %")),
                ("threshold_5", models.PositiveSmallIntegerField(default=85, verbose_name="Пятёрка от, %")),
                ("threshold_4", models.PositiveSmallIntegerField(default=65, verbose_name="Четвёрка от, %")),
                ("threshold_3", models.PositiveSmallIntegerField(default=40, verbose_name="Тройка от, %")),
                ("fo_max", models.PositiveSmallIntegerField(default=10, verbose_name="Максимум ФО")),
                ("edit_days", models.PositiveSmallIntegerField(default=7, verbose_name="Учитель правит оценку, дней")),
                (
                    "year",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scale",
                        to="academics.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шкала оценивания",
                "verbose_name_plural": "Шкалы оценивания",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("slot", models.PositiveSmallIntegerField(verbose_name="Номер урока")),
                ("room", models.CharField(blank=True, max_length=40, verbose_name="Кабинет")),
                (
                    "status",
                    models.CharField(
                        choices=[("planned", "По плану"), ("cancelled", "Отменён"), ("moved", "Перенесён")],
                        default="planned",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200, verbose_name="Причина")),
                ("moved_from_date", models.DateField(blank=True, null=True, verbose_name="Перенесён с даты")),
                (
                    "moved_from_slot",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Перенесён с урока"),
                ),
                ("topic", models.CharField(blank=True, max_length=200, verbose_name="Тема")),
                ("homework", models.TextField(blank=True, verbose_name="Домашнее задание")),
                (
                    "kind",
                    models.CharField(
                        choices=[("fo", "ФО"), ("sor", "СОР"), ("soch", "СОЧ")],
                        default="fo",
                        max_length=4,
                        verbose_name="Вид оценивания",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Номер СОР или СОЧ")),
                ("max_score", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Максимум баллов")),
                ("note", models.CharField(blank=True, max_length=120, verbose_name="Примечание")),
                ("marked_at", models.DateTimeField(blank=True, null=True, verbose_name="Посещаемость сохранена")),
                ("reminded_at", models.DateTimeField(blank=True, null=True, verbose_name="Напоминание ушло")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Заведён")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменён")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="academics.course",
                        verbose_name="Журнал",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто завёл",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отметил",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substituted_lessons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Замена",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ("date", "slot", "id"),
            },
        ),
        migrations.CreateModel(
            name="LessonRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("wanted", models.CharField(blank=True, max_length=200, verbose_name="Куда удобно")),
                ("reason", models.CharField(max_length=300, verbose_name="Причина")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ждёт"), ("approved", "Одобрено"), ("rejected", "Отклонено")],
                        default="pending",
                        max_length=8,
                        verbose_name="Состояние",
                    ),
                ),
                ("answer", models.CharField(blank=True, max_length=300, verbose_name="Ответ")),
                ("decided_at", models.DateTimeField(blank=True, null=True, verbose_name="Решено")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Подана")),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто решил",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="academics.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просьба о переносе",
                "verbose_name_plural": "Просьбы о переносе",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LessonSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekday", models.PositiveSmallIntegerField(verbose_name="День недели")),
                ("slot", models.PositiveSmallIntegerField(verbose_name="Номер урока")),
                ("room", models.CharField(blank=True, max_length=40, verbose_name="Кабинет")),
                ("starts", models.DateField(verbose_name="С")),
                ("ends", models.DateField(verbose_name="По")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Заведена")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="academics.course",
                        verbose_name="Журнал",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто завёл",
                    ),
                ),
            ],
            options={
                "verbose_name": "Серия уроков",
                "verbose_name_plural": "Серии уроков",
                "ordering": ("weekday", "slot"),
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="academics.lessonseries",
                verbose_name="Серия",
            ),
        ),
        migrations.CreateModel(
            name="ParentReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                (
                    "period_kind",
                    models.CharField(
                        choices=[("month", "Месяц"), ("quarter", "Четверть")], max_length=8, verbose_name="Период"
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                ("title", models.CharField(max_length=60, verbose_name="Название периода")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("checked", "Проверен"),
                            ("exported", "Выгружен"),
                            ("sent", "Отправлен родителям"),
                        ],
                        default="draft",
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
                ("built_at", models.DateTimeField(verbose_name="Собран")),
                ("fingerprint", models.CharField(blank=True, max_length=64, verbose_name="Отпечаток данных")),
                ("curator_word", models.TextField(blank=True, verbose_name="Слово куратора")),
                ("checked_at", models.DateTimeField(blank=True, null=True, verbose_name="Проверен")),
                ("exported_at", models.DateTimeField(blank=True, null=True, verbose_name="Выгружен")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Отправлен родителям")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто проверил",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отправил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_reports",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт родителям",
                "verbose_name_plural": "Отчёты родителям",
                "ordering": ("-period_start", "student__last_name", "student__first_name"),
            },
        ),
        migrations.CreateModel(
            name="Quarter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField(verbose_name="Номер")),
                ("title", models.CharField(max_length=40, verbose_name="Название")),
                ("starts", models.DateField(verbose_name="Начало")),
                ("ends", models.DateField(verbose_name="Конец")),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="Итоги закрыты")),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто закрыл",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarters",
                        to="academics.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Четверть",
                "verbose_name_plural": "Четверти",
                "ordering": ("year", "number"),
            },
        ),
        migrations.CreateModel(
            name="QuarterResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grade", models.PositiveSmallIntegerField(verbose_name="Итог")),
                (
                    "computed_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Расчётный процент"
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200, verbose_name="Причина отличия от расчёта")),
                ("set_at", models.DateTimeField(auto_now=True, verbose_name="Выставлен")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="academics.course",
                        verbose_name="Журнал",
                    ),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="academics.quarter",
                        verbose_name="Четверть",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто выставил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarter_results",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Итог четверти",
                "verbose_name_plural": "Итоги четверти",
            },
        ),
        migrations.CreateModel(
            name="ReportLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("attendance", "Посещаемость"),
                            ("grades", "Оценки"),
                            ("exams", "Экзамены и вузы"),
                            ("documents", "Документы"),
                            ("discipline", "Дисциплина"),
                        ],
                        max_length=12,
                        verbose_name="Раздел",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("title", models.CharField(max_length=120, verbose_name="Подпись")),
                ("value", models.CharField(blank=True, max_length=120, verbose_name="Значение")),
                ("note", models.CharField(blank=True, max_length=300, verbose_name="Примечание")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="academics.parentreport",
                        verbose_name="Отчёт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка отчёта",
                "verbose_name_plural": "Строки отчёта",
                "ordering": ("report", "section", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ReportSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("month", "Последняя пятница месяца и после четверти"),
                            ("quarter", "Только после закрытия четверти"),
                        ],
                        default="month",
                        max_length=8,
                        verbose_name="Когда собирать",
                    ),
                ),
                ("section_attendance", models.BooleanField(default=True, verbose_name="Посещаемость по урокам")),
                ("section_grades", models.BooleanField(default=True, verbose_name="Оценки по предметам")),
                ("section_exams", models.BooleanField(default=True, verbose_name="Экзамены и вузы")),
                ("section_documents", models.BooleanField(default=True, verbose_name="Документы для поступления")),
                ("section_curator", models.BooleanField(default=True, verbose_name="Слово куратора")),
                ("section_discipline", models.BooleanField(default=False, verbose_name="Замечания по дисциплине")),
                (
                    "year",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_settings",
                        to="academics.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки отчётов",
                "verbose_name_plural": "Настройки отчётов",
            },
        ),
        migrations.CreateModel(
            name="StreamPart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_streams",
                        to="academics.cohort",
                        verbose_name="Часть",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="academics.cohort",
                        verbose_name="Поток",
                    ),
                ),
            ],
            options={
                "verbose_name": "Часть потока",
                "verbose_name_plural": "Части потоков",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("room", models.CharField(blank=True, max_length=40, verbose_name="Кабинет")),
                ("is_fictional", models.BooleanField(default=False, verbose_name="Вымышленный")),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, related_name="teachers", to="academics.subject", verbose_name="Предметы"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учётная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль учителя",
                "verbose_name_plural": "Профили учителей",
            },
        ),
        migrations.CreateModel(
            name="Bell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField(verbose_name="Урок")),
                ("starts", models.TimeField(verbose_name="Начало")),
                ("ends", models.TimeField(verbose_name="Конец")),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bells",
                        to="academics.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звонок",
                "verbose_name_plural": "Звонки",
                "ordering": ("year", "number"),
                "constraints": [models.UniqueConstraint(fields=("year", "number"), name="unique_bell_number")],
            },
        ),
        migrations.CreateModel(
            name="CohortMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("since", models.DateField(verbose_name="С")),
                ("until", models.DateField(blank=True, null=True, verbose_name="По")),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="academics.cohort",
                        verbose_name="Состав",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_memberships",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Членство в подгруппе",
                "verbose_name_plural": "Членства в подгруппах",
                "ordering": ("cohort", "student"),
                "indexes": [models.Index(fields=["student", "until"], name="academics_c_student_2d64cf_idx")],
            },
        ),
        migrations.CreateModel(
            name="Excuse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("starts", models.DateField(verbose_name="С")),
                ("ends", models.DateField(verbose_name="По")),
                ("reason", models.CharField(max_length=200, verbose_name="Причина")),
                (
                    "document",
                    models.CharField(
                        choices=[
                            ("certificate", "Справка"),
                            ("parents", "Заявление родителей"),
                            ("order", "Приказ школы"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=12,
                        verbose_name="Вид документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        storage=academics.models._private_storage,
                        upload_to=academics.models.excuse_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "created_by_title",
                    models.CharField(blank=True, max_length=250, verbose_name="Автор на момент удаления"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Оформлена")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто оформил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excuses",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уважительная причина",
                "verbose_name_plural": "Уважительные причины",
                "ordering": ("-starts", "-id"),
                "indexes": [models.Index(fields=["student", "starts", "ends"], name="academics_e_student_0328c0_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends__gte", models.F("starts"))), name="excuse_ends_after_starts"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата")),
                ("title", models.CharField(max_length=80, verbose_name="Название")),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="academics.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Праздник",
                "verbose_name_plural": "Праздники",
                "ordering": ("date",),
                "constraints": [models.UniqueConstraint(fields=("year", "date"), name="unique_holiday_date")],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("value", models.PositiveSmallIntegerField(verbose_name="Балл")),
                ("comment", models.CharField(blank=True, max_length=300, verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Поставлена")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменена")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто поставил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="academics.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "indexes": [models.Index(fields=["student", "lesson"], name="academics_g_student_6a0f0f_idx")],
                "constraints": [models.UniqueConstraint(fields=("lesson", "student"), name="unique_lesson_grade")],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                (
                    "mark",
                    models.CharField(
                        choices=[("absent", "Не был"), ("late", "Опоздал")], max_length=6, verbose_name="Отметка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Отмечен")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Изменён")),
                (
                    "noted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отметил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_attendance",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="academics.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отметка посещаемости",
                "verbose_name_plural": "Отметки посещаемости",
                "indexes": [models.Index(fields=["student", "lesson"], name="academics_a_student_5a5c4b_idx")],
                "constraints": [models.UniqueConstraint(fields=("lesson", "student"), name="unique_lesson_attendance")],
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["date", "slot"], name="academics_l_date_9b7fb6_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["course", "date"], name="academics_l_course__938b52_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["teacher", "date"], name="academics_l_teacher_131af2_idx"),
        ),
        migrations.AddConstraint(
            model_name="parentreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("student", "period_kind", "period_start"),
                name="one_report_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="quarter",
            constraint=models.UniqueConstraint(fields=("year", "number"), name="unique_quarter_number"),
        ),
        migrations.AddConstraint(
            model_name="quarterresult",
            constraint=models.UniqueConstraint(fields=("course", "student", "quarter"), name="unique_quarter_result"),
        ),
        migrations.AddConstraint(
            model_name="streampart",
            constraint=models.UniqueConstraint(fields=("stream", "part"), name="unique_stream_part"),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("subject", "teacher", "cohort"),
                name="unique_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True), ("kind", "group")),
                fields=("group",),
                name="one_group_cohort_per_group",
            ),
        ),
    ]
