# Generated by Django 5.2.17 on 2026-09-29 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_bell_schedules_and_report_word"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="unique_course",
        ),
        migrations.AddField(
            model_name="cohort",
            name="room",
            field=models.CharField(blank=True, max_length=40, verbose_name="Основной кабинет"),
        ),
        migrations.AddField(
            model_name="cohort",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kind": "stream"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inner_subgroups",
                to="academics.cohort",
                verbose_name="Поток подгруппы",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Учитель",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Учитель",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("subject", "teacher", "cohort"),
                name="unique_course",
                nulls_distinct=False,
            ),
        ),
    ]
