# Generated by Django 5.2.17 on 2026-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_subgroup_in_stream_and_optional_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="arrived_at",
            field=models.TimeField(blank=True, null=True, verbose_name="Пришёл в"),
        ),
    ]
