# Generated by Django 5.2.17 on 2026-09-30 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


#: казахские названия предметов школы (книга расписания 2026–2027) — для
#: отчётов родителям на казахском; администратор правит в «Предметах»
TITLES_KK = {
    "Алгебра": "Алгебра",
    "Геометрия": "Геометрия",
    "Математика": "Математика",
    "Физика": "Физика",
    "Химия": "Химия",
    "Биология": "Биология",
    "География": "География",
    "Информатика": "Информатика",
    "История Казахстана": "Қазақстан тарихы",
    "Всемирная история": "Дүниежүзі тарихы",
    "Казахский язык": "Қазақ тілі",
    "Казахский язык и литература": "Қазақ тілі мен әдебиеті",
    "Казахская литература": "Қазақ әдебиеті",
    "Қазақ тілі": "Қазақ тілі",
    "Қазақ әдебиеті": "Қазақ әдебиеті",
    "Русский язык": "Орыс тілі",
    "Русская литература": "Орыс әдебиеті",
    "Русский язык и литература": "Орыс тілі мен әдебиеті",
    "Орыс тілі мен әдебиеті": "Орыс тілі мен әдебиеті",
    "Английский язык": "Ағылшын тілі",
    "Английский язык (EEP)": "Ағылшын тілі (EEP)",
    "Английский язык (GE)": "Ағылшын тілі (GE)",
    "Основы права": "Құқық негіздері",
    "Классный час": "Сынып сағаты",
    "Профориентация": "Кәсіптік бағдар",
    "Физкультура": "Дене шынықтыру",
    "Физическая культура": "Дене шынықтыру",
    "Global Perspectives": "Global Perspectives",
    "Creative Writing": "Creative Writing",
    "SAT": "SAT",
    "SAT Math": "SAT Math",
    "IELTS": "IELTS",
}


def fill(apps, schema_editor):
    """Казахские названия предметов и раздел «GE / EEP» у журналов английского.

    Пишется через `update()` (миграция доменных записей). Журналы SAT
    делятся на Verbal и Math по учителю — это `manage.py report_roles`.
    """
    Subject = apps.get_model("academics", "Subject")
    Course = apps.get_model("academics", "Course")
    for title, title_kk in TITLES_KK.items():
        Subject.objects.filter(title=title, title_kk="").update(title_kk=title_kk)
    english = Subject.objects.filter(title__in=("Английский язык (EEP)", "Английский язык (GE)"))
    Course.objects.filter(subject__in=english, report_role="").update(report_role="eep")


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_late_arrival_time"),
        ("students", "0030_group_letter_and_home_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnglishLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[("A1", "A1"), ("A2", "A2"), ("B1", "B1"), ("B2", "B2"), ("C1", "C1"), ("C2", "C2")],
                        max_length=2,
                        verbose_name="Уровень",
                    ),
                ),
                ("since", models.DateField(verbose_name="С")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Внесён")),
            ],
            options={
                "verbose_name": "Уровень английского",
                "verbose_name_plural": "Уровни английского",
                "ordering": ("student", "-since", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ReportReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("eep", "GE / EEP"),
                            ("sat_verbal", "SAT Verbal"),
                            ("sat_math", "SAT Math"),
                            ("subject", "Предмет"),
                        ],
                        max_length=12,
                        verbose_name="Вид",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("teacher_name", models.CharField(blank=True, max_length=200, verbose_name="Учитель")),
                ("subject_title", models.CharField(blank=True, max_length=120, verbose_name="Предмет")),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                ("by_ai", models.BooleanField(default=False, verbose_name="Черновик ИИ")),
            ],
            options={
                "verbose_name": "Отзыв в отчёте",
                "verbose_name_plural": "Отзывы в отчёте",
                "ordering": ("report", "order", "id"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="parentreport",
            name="one_report_per_period",
        ),
        migrations.AddField(
            model_name="course",
            name="report_role",
            field=models.CharField(
                blank=True,
                choices=[("", "нет"), ("eep", "GE / EEP"), ("sat_verbal", "SAT Verbal"), ("sat_math", "SAT Math")],
                default="",
                max_length=12,
                verbose_name="Раздел отчёта родителям",
            ),
        ),
        migrations.AddField(
            model_name="parentreport",
            name="character",
            field=models.TextField(blank=True, verbose_name="Характеристика"),
        ),
        migrations.AddField(
            model_name="parentreport",
            name="draft_note",
            field=models.CharField(blank=True, max_length=250, verbose_name="Почему черновика нет"),
        ),
        migrations.AddField(
            model_name="parentreport",
            name="draft_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "не заказан"),
                    ("pending", "пишется"),
                    ("done", "написан"),
                    ("skipped", "данных нет"),
                    ("failed", "ИИ недоступен"),
                ],
                default="",
                max_length=8,
                verbose_name="Черновик ИИ",
            ),
        ),
        migrations.AddField(
            model_name="parentreport",
            name="drafted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Черновик написан"),
        ),
        migrations.AddField(
            model_name="parentreport",
            name="language",
            field=models.CharField(
                choices=[("ru", "Русский"), ("kk", "Казахский")], default="ru", max_length=2, verbose_name="Язык"
            ),
        ),
        migrations.AddField(
            model_name="parentreport",
            name="mock_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий по пробнику"),
        ),
        migrations.AddField(
            model_name="parentreport",
            name="summary",
            field=models.TextField(blank=True, verbose_name="Итоги и рекомендации"),
        ),
        migrations.AddField(
            model_name="parentreport",
            name="template",
            field=models.CharField(
                choices=[
                    ("standard", "Стандартный"),
                    ("review", "Вариант 1 · отзыв об успеваемости"),
                    ("progress", "Вариант 2 · отчёт о прогрессе"),
                ],
                default="standard",
                max_length=10,
                verbose_name="Вид отчёта",
            ),
        ),
        migrations.AddField(
            model_name="reportline",
            name="code",
            field=models.CharField(blank=True, max_length=24, verbose_name="Код строки"),
        ),
        migrations.AddField(
            model_name="subject",
            name="title_kk",
            field=models.CharField(blank=True, max_length=100, verbose_name="Название на казахском"),
        ),
        migrations.AlterField(
            model_name="parentreport",
            name="period_kind",
            field=models.CharField(
                choices=[("month", "Месяц"), ("quarter", "Четверть"), ("custom", "Свой период")],
                max_length=8,
                verbose_name="Период",
            ),
        ),
        migrations.AlterField(
            model_name="reportline",
            name="section",
            field=models.CharField(
                choices=[
                    ("attendance", "Посещаемость"),
                    ("grades", "Оценки"),
                    ("exams", "Экзамены и вузы"),
                    ("documents", "Документы"),
                    ("discipline", "Дисциплина"),
                    ("ielts", "Пробник IELTS"),
                    ("sat", "Пробник SAT"),
                    ("profile", "Уровень английского и спорт"),
                ],
                max_length=12,
                verbose_name="Раздел",
            ),
        ),
        migrations.AddConstraint(
            model_name="parentreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("student", "template", "language", "period_kind", "period_start", "period_end"),
                name="one_report_per_period",
            ),
        ),
        migrations.AddField(
            model_name="englishlevel",
            name="set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто внёс",
            ),
        ),
        migrations.AddField(
            model_name="englishlevel",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="english_levels",
                to="students.student",
                verbose_name="Ученик",
            ),
        ),
        migrations.AddField(
            model_name="reportreview",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="academics.course",
                verbose_name="Журнал",
            ),
        ),
        migrations.AddField(
            model_name="reportreview",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="academics.parentreport",
                verbose_name="Отчёт",
            ),
        ),
        migrations.AddConstraint(
            model_name="englishlevel",
            constraint=models.UniqueConstraint(fields=("student", "since"), name="one_english_level_per_day"),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
