# Generated by Django 5.2.17 on 2026-09-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_school_report_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentreport",
            name="texts_edited_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Тексты правил человек"),
        ),
    ]
