# Generated by Django 5.2.17 on 2026-09-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_report_texts_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentreport",
            name="mock_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий по Mock Test"),
        ),
        migrations.AlterField(
            model_name="reportline",
            name="section",
            field=models.CharField(
                choices=[
                    ("attendance", "Посещаемость"),
                    ("grades", "Оценки"),
                    ("exams", "Экзамены и вузы"),
                    ("documents", "Документы"),
                    ("discipline", "Дисциплина"),
                    ("ielts", "IELTS Mock Test"),
                    ("sat", "SAT Mock Test"),
                    ("profile", "Уровень английского и спорт"),
                ],
                max_length=12,
                verbose_name="Раздел",
            ),
        ),
    ]
