# Generated by Django 5.2.17 on 2026-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_no_common_bells"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="in_lms",
            field=models.BooleanField(default=True, verbose_name="Ведётся в LMS"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Показывать в списках"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="scheme",
            field=models.CharField(
                choices=[("kz", "ФО, СОР и СОЧ, итог за четверть"), ("fo", "Только ФО из 10")],
                default="kz",
                max_length=2,
                verbose_name="Схема оценивания",
            ),
        ),
    ]
