# Generated by Django 5.2.17 on 2026-10-08 08:22

from django.db import migrations, models


def mark_career_subject(apps, schema_editor):
    """Профориентация — предмет профориентации: её учителю открыт раздел «Профтест».

    Пишется через `update()`: сигнал журнала у миграции автора не имеет.
    """
    Subject = apps.get_model("academics", "Subject")
    Subject.objects.filter(title__icontains="профориентац").update(is_career=True)


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_subject_in_lms"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_career",
            field=models.BooleanField(default=False, verbose_name="Предмет профориентации"),
        ),
        migrations.RunPython(mark_career_subject, migrations.RunPython.noop),
    ]
