# Generated by Django 5.1.5 on 2026-08-21 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=32, verbose_name="Роль автора")),
                ("domain_code", models.CharField(max_length=32, verbose_name="Домен")),
                ("command", models.CharField(blank=True, max_length=64, verbose_name="Команда")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("paste", "Вставленный текст"),
                            ("file", "Файл"),
                            ("image", "Изображение"),
                            ("web_sync", "Фоновая сверка"),
                            ("manual", "Заведено руками"),
                        ],
                        max_length=16,
                        verbose_name="Тип источника",
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=500, verbose_name="Ссылка на источник")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "Ждёт решения"),
                            ("applied", "Применено"),
                            ("partially_applied", "Применено частично"),
                            ("rejected", "Отклонено"),
                            ("reverted", "Откачено"),
                        ],
                        default="draft",
                        max_length=24,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Решено")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SuggestionChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_label", models.CharField(max_length=100, verbose_name="Модель")),
                ("object_id", models.CharField(blank=True, max_length=64, verbose_name="Объект")),
                ("field_name", models.CharField(max_length=100, verbose_name="Поле")),
                ("old_value", models.TextField(blank=True, verbose_name="Было")),
                ("new_value", models.TextField(blank=True, verbose_name="Стало")),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4, verbose_name="Уверенность"),
                ),
                ("source_ref", models.CharField(blank=True, max_length=500, verbose_name="Ссылка на источник")),
                ("source_quote", models.TextField(blank=True, verbose_name="Фрагмент источника")),
                ("is_accepted", models.BooleanField(default=False, verbose_name="Принято")),
                ("is_applied", models.BooleanField(default=False, verbose_name="Применено")),
                ("conflict", models.CharField(blank=True, max_length=250, verbose_name="Конфликт")),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_changes",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="suggestions.suggestion",
                        verbose_name="Предложение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение в предложении",
                "verbose_name_plural": "Изменения в предложениях",
                "ordering": ("confidence", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="suggestion",
            index=models.Index(fields=["domain_code", "status", "-created_at"], name="suggestions_domain__bedf87_idx"),
        ),
    ]
