# Generated by Django 5.1.5 on 2026-08-21 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
        ("students", "0001_initial"),
        ("suggestions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayAssistLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prompt", models.TextField(verbose_name="Запрос ученика")),
                ("questions", models.TextField(verbose_name="Вопросы от ИИ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assist_logs",
                        to="roadmap.essay",
                        verbose_name="Эссе",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essay_assists",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа с ИИ по эссе",
                "verbose_name_plural": "Работа с ИИ по эссе",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                ("purpose", models.CharField(max_length=64, verbose_name="Назначение")),
                ("model", models.CharField(blank=True, max_length=100, verbose_name="Модель")),
                ("external_id", models.CharField(blank=True, max_length=100, verbose_name="Идентификатор вызова")),
                ("request_payload", models.TextField(blank=True, verbose_name="Отправлено")),
                ("response_payload", models.TextField(blank=True, verbose_name="Получено")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто вызвал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вызов модели",
                "verbose_name_plural": "Журнал вызовов модели",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["-created_at"], name="suggestions_created_292ec8_idx"),
                    models.Index(fields=["purpose"], name="suggestions_purpose_cded03_idx"),
                ],
            },
        ),
    ]
