# Generated by Django 5.1.5 on 2026-08-24 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0002_essayassistlog_llmcall"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcall",
            name="cost",
            field=models.DecimalField(decimal_places=5, default=0, max_digits=9, verbose_name="Стоимость, $"),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="duration_ms",
            field=models.PositiveIntegerField(default=0, verbose_name="Длительность, мс"),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="error",
            field=models.CharField(blank=True, max_length=250, verbose_name="Что пошло не так"),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="is_ok",
            field=models.BooleanField(default=True, verbose_name="Успешно"),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="provider",
            field=models.CharField(blank=True, max_length=32, verbose_name="Провайдер"),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="role",
            field=models.CharField(blank=True, max_length=32, verbose_name="Роль"),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="tokens_in",
            field=models.PositiveIntegerField(default=0, verbose_name="Токенов на входе"),
        ),
        migrations.AddField(
            model_name="llmcall",
            name="tokens_out",
            field=models.PositiveIntegerField(default=0, verbose_name="Токенов на выходе"),
        ),
        migrations.AddField(
            model_name="suggestionchange",
            name="new_object_key",
            field=models.CharField(blank=True, max_length=64, verbose_name="Новая запись"),
        ),
        migrations.AlterField(
            model_name="llmcall",
            name="purpose",
            field=models.CharField(max_length=64, verbose_name="Операция"),
        ),
        migrations.AddIndex(
            model_name="llmcall",
            index=models.Index(fields=["role", "-created_at"], name="suggestions_role_4c2f26_idx"),
        ),
    ]
