# Generated by Django 5.1.5 on 2026-08-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0003_phase20_llm_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="Название")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_threads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диалог помощника",
                "verbose_name_plural": "Диалоги помощника",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "author",
                    models.CharField(
                        choices=[("user", "Человек"), ("assistant", "Помощник")], max_length=12, verbose_name="Кто"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("lines", models.TextField(blank=True, verbose_name="Строки")),
                ("command", models.CharField(blank=True, max_length=64, verbose_name="Команда")),
                ("offline", models.BooleanField(default=True, verbose_name="Собрано правилами")),
                ("affected", models.PositiveIntegerField(default=0, verbose_name="Затронет учеников")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_messages",
                        to="suggestions.suggestion",
                        verbose_name="Предложение",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="suggestions.assistantthread",
                        verbose_name="Диалог",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение помощника",
                "verbose_name_plural": "Сообщения помощника",
                "ordering": ("created_at", "id"),
            },
        ),
    ]
