# Generated by Django 5.1.5 on 2026-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0004_assistantthread_assistantmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmcall",
            name="searches",
            field=models.PositiveIntegerField(default=0, verbose_name="Поисковых запросов"),
        ),
    ]
