# Generated by Django 5.1.5 on 2026-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0005_phase27_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="reject_reason",
            field=models.CharField(blank=True, max_length=250, verbose_name="Причина отклонения"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("paste", "Вставленный текст"),
                    ("file", "Файл"),
                    ("image", "Изображение"),
                    ("web_sync", "Фоновая сверка"),
                    ("manual", "Заведено руками"),
                    ("student", "Внёс ученик"),
                ],
                max_length=16,
                verbose_name="Тип источника",
            ),
        ),
    ]
