# Generated by Django 5.1.5 on 2026-08-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0006_phase37_student_proposals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("paste", "Вставленный текст"),
                    ("file", "Файл"),
                    ("image", "Изображение"),
                    ("web_sync", "Фоновая сверка"),
                    ("manual", "Заведено руками"),
                    ("student", "Внёс ученик"),
                    ("plan", "План по вузу"),
                ],
                max_length=16,
                verbose_name="Тип источника",
            ),
        ),
    ]
