# Generated by Django 5.1.15 on 2026-09-08 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0007_phase41_plan_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_suggestions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто решил",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="resolved_role",
            field=models.CharField(blank=True, max_length=32, verbose_name="Роль решившего"),
        ),
    ]
