# Generated by Django 5.1.15 on 2026-09-08 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0008_phase60"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда передано"),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="escalated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_suggestions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто передал",
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="escalation_comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Комментарий при передаче"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("paste", "Вставленный текст"),
                    ("file", "Файл"),
                    ("image", "Изображение"),
                    ("web_sync", "Фоновая сверка"),
                    ("manual", "Заведено руками"),
                    ("student", "Внёс ученик"),
                    ("plan", "План по вузу"),
                    ("document", "Загрузил документ"),
                ],
                max_length=16,
                verbose_name="Тип источника",
            ),
        ),
    ]
