# Generated by Django 5.2.17 on 2026-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0009_phase62"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="resolved_by_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Кто решил, на момент удаления"),
        ),
    ]
