# Generated by Django 5.2.17 on 2026-09-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0010_phase67"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestionchange",
            name="superseded_value",
            field=models.TextField(blank=True, verbose_name="Внесено куратором"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending", "Ждёт решения"),
                    ("applied", "Применено"),
                    ("partially_applied", "Применено частично"),
                    ("rejected", "Отклонено"),
                    ("reverted", "Откачено"),
                    ("superseded", "Перекрыто записью куратора"),
                ],
                default="draft",
                max_length=24,
                verbose_name="Статус",
            ),
        ),
    ]
