# Generated by Django 5.2.17 on 2026-09-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0012_close_stale_sync_suggestions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("paste", "Вставленный текст"),
                    ("file", "Файл"),
                    ("image", "Изображение"),
                    ("web_sync", "Фоновая сверка"),
                    ("manual", "Заведено руками"),
                    ("student", "Внёс ученик"),
                    ("plan", "План по вузу"),
                    ("document", "Загрузил документ"),
                    ("assistant", "Собрал помощник"),
                ],
                max_length=16,
                verbose_name="Тип источника",
            ),
        ),
    ]
