# Generated by Django 5.1.5 on 2026-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OlympiadSubject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать в списке выбора")),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("natural", "Естественные науки"),
                            ("exact", "Точные науки"),
                            ("humanities", "Гуманитарные науки"),
                            ("languages", "Языки"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="Направление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет олимпиады",
                "verbose_name_plural": "Предметы олимпиад",
                "ordering": ("sort_order", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SportType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать в списке выбора")),
                ("sort_order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("team", "Командный"),
                            ("individual", "Индивидуальный"),
                            ("martial", "Единоборства"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид спорта",
                "verbose_name_plural": "Виды спорта",
                "ordering": ("sort_order", "name"),
                "abstract": False,
            },
        ),
    ]
