# Generated by Django 5.2.17 on 2026-09-20 19:51

"""Направление предмета олимпиады — текстом: из списка или своё.

До правки в поле лежал код одного из пяти вариантов. Теперь там то, что видит
человек: коды переводятся в названия, дальше Арман вводит своё. Числового
«порядка» у предметов больше нет — список по алфавиту. Запись через `update()`:
это смена представления, а не правка значения, журналу о ней сказать нечего.
"""

from django.db import migrations, models

TITLES = {
    "natural": "Естественные науки",
    "exact": "Точные науки",
    "humanities": "Гуманитарные науки",
    "languages": "Языки",
    "other": "Прочее",
}


def codes_to_titles(apps, schema_editor):
    subjects = apps.get_model("directories", "OlympiadSubject")
    for code, title in TITLES.items():
        subjects.objects.filter(area=code).update(area=title)


def titles_to_codes(apps, schema_editor):
    subjects = apps.get_model("directories", "OlympiadSubject")
    for code, title in TITLES.items():
        subjects.objects.filter(area=title).update(area=code)
    subjects.objects.exclude(area__in=TITLES).update(area="other")


class Migration(migrations.Migration):

    dependencies = [
        ("directories", "0005_phase59_ent_to_archive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="olympiadsubject",
            options={
                "ordering": ("name",),
                "verbose_name": "Предмет олимпиады",
                "verbose_name_plural": "Предметы олимпиад",
            },
        ),
        migrations.AlterField(
            model_name="olympiadsubject",
            name="area",
            field=models.CharField(default="Прочее", max_length=80, verbose_name="Направление"),
        ),
        migrations.RunPython(codes_to_titles, titles_to_codes),
    ]
