# Generated by Django 5.1.5 on 2026-08-21 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("universities", "0002_admissionrequirement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("test", "Тест"),
                            ("essay", "Эссе"),
                            ("documents", "Документы"),
                            ("university", "Вузы"),
                            ("portfolio", "Портфолио"),
                            ("finance", "Финансы"),
                        ],
                        max_length=16,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "Высокий"), ("medium", "Средний"), ("low", "Низкий")],
                        default="medium",
                        max_length=8,
                        verbose_name="Приоритет",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("due_month", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Месяц срока")),
                ("due_day", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="День срока")),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Для выпуска"),
                ),
                ("grade", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Для класса")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
            ],
            options={
                "verbose_name": "Шаблон задачи",
                "verbose_name_plural": "Шаблоны задач",
                "ordering": ("due_month", "due_day", "title"),
            },
        ),
        migrations.CreateModel(
            name="Essay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "essay_type",
                    models.CharField(
                        choices=[
                            ("personal_statement", "Personal Statement"),
                            ("supplemental", "Supplemental"),
                            ("motivation", "Мотивационное письмо"),
                            ("scholarship", "Для стипендии"),
                        ],
                        max_length=24,
                        verbose_name="Тип",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("review", "На проверке"),
                            ("revision", "Правки"),
                            ("done", "Готово"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                (
                    "curator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curated_essays",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Куратор",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто — общее эссе",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="essays",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essays",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эссе",
                "verbose_name_plural": "Эссе",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="EssayVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField(verbose_name="Номер версии")),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                ("word_count", models.PositiveSmallIntegerField(default=0, verbose_name="Слов")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="roadmap.essay",
                        verbose_name="Эссе",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия эссе",
                "verbose_name_plural": "Версии эссе",
                "ordering": ("-number",),
            },
        ),
        migrations.CreateModel(
            name="EssayComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "essay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="roadmap.essay",
                        verbose_name="Эссе",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="roadmap.essayversion",
                        verbose_name="Версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к эссе",
                "verbose_name_plural": "Комментарии к эссе",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("test", "Тест"),
                            ("essay", "Эссе"),
                            ("documents", "Документы"),
                            ("university", "Вузы"),
                            ("portfolio", "Портфолио"),
                            ("finance", "Финансы"),
                        ],
                        max_length=16,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "Высокий"), ("medium", "Средний"), ("low", "Низкий")],
                        default="medium",
                        max_length=8,
                        verbose_name="Приоритет",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Сделать"),
                            ("in_progress", "В работе"),
                            ("review", "На проверке"),
                            ("done", "Готово"),
                        ],
                        default="todo",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True, verbose_name="Срок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Завершена")),
                (
                    "admission_round",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если заполнено — срок берётся из дедлайна раунда",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="universities.admissionround",
                        verbose_name="Раунд вуза",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="roadmap.tasktemplate",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ("due_date", "-priority", "id"),
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="roadmap.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к задаче",
                "verbose_name_plural": "Комментарии к задачам",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="essayversion",
            constraint=models.UniqueConstraint(fields=("essay", "number"), name="uniq_essay_version_number"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["student", "status"], name="roadmap_tas_student_b4b1e5_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="roadmap_tas_due_dat_64bbef_idx"),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("admission_round__isnull", False)),
                fields=("student", "admission_round"),
                name="uniq_task_per_student_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("template__isnull", False)),
                fields=("student", "template"),
                name="uniq_task_per_student_template",
            ),
        ),
    ]
