# Generated by Django 5.1.5 on 2026-08-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0002_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essay",
            name="essay_type",
            field=models.CharField(
                choices=[
                    ("personal_statement", "Personal Statement"),
                    ("supplemental", "Дополнительное эссе"),
                    ("motivation", "Мотивационное письмо"),
                    ("scholarship", "Для стипендии"),
                ],
                max_length=24,
                verbose_name="Тип",
            ),
        ),
    ]
