# Generated by Django 5.1.5 on 2026-08-31 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0003_russian_labels"),
        ("students", "0013_phase39_exam_goals"),
        ("universities", "0007_phase20_llm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="exam_goal",
            field=models.ForeignKey(
                blank=True,
                help_text="Если заполнено — срок берётся из даты регистрации или экзамена",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="students.examgoal",
                verbose_name="Цель по экзамену",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True), ("exam_goal__isnull", False)),
                fields=("student", "exam_goal"),
                name="unique_task_per_exam_goal",
            ),
        ),
    ]
