# Generated by Django 5.1.5 on 2026-08-31 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0004_phase39_task_exam_goal"),
        ("students", "0013_phase39_exam_goals"),
        ("suggestions", "0007_phase41_plan_source"),
        ("universities", "0008_phase40_selection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("none", "Не запускалась"),
                            ("running", "Идёт"),
                            ("done", "Готова"),
                            ("failed", "Не получилась"),
                        ],
                        default="none",
                        max_length=12,
                        verbose_name="Генерация",
                    ),
                ),
                ("generation_offline", models.BooleanField(default=True, verbose_name="Собрана правилами")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "admission_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans",
                        to="universities.admissionround",
                        verbose_name="Раунд подачи",
                    ),
                ),
                (
                    "pending_suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plans",
                        to="suggestions.suggestion",
                        verbose_name="Предложение задач",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_plans",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "План поступления",
                "verbose_name_plural": "Планы поступления",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="task",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="roadmap.applicationplan",
                verbose_name="План",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("student", "program"),
                name="unique_active_plan_per_program",
            ),
        ),
    ]
