# Generated by Django 5.1.5 on 2026-08-31 11:21

import django.db.models.deletion
from django.db import migrations, models




def seed_doc_types(apps, schema_editor):
    EssayDocType = apps.get_model("roadmap", "EssayDocType")
    rows = (
        ("personal_statement", "Personal Statement", "Рассказ о себе: кто вы и почему именно эта программа.", 650, 10),
        ("motivation_letter", "Motivation Letter", "Почему вы хотите учиться здесь и что дадите взамен.", 500, 20),
        ("research_statement", "Research Statement", "Ваши исследовательские интересы и планы.", 800, 30),
        ("cover_letter", "Cover Letter", "Сопроводительное письмо к заявке.", 400, 40),
        ("free_form", "Free Form Essay", "Свободная форма без заданного вопроса.", 650, 50),
        ("thematic", "Thematic Essay", "Эссе на заданную тему или вопрос.", 500, 60),
        ("study_plan", "Study Plan", "План обучения и целей на программе.", 700, 70),
        ("supplemental", "Supplemental Essay", "Дополнительное эссе конкретного вуза.", 300, 80),
        ("no_type", "Без типа", "Черновик без привязки к типу документа.", 650, 90),
    )
    for code, name, desc, limit, order in rows:
        EssayDocType.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": desc, "default_word_limit": limit, "order": order},
        )


def unseed_doc_types(apps, schema_editor):
    EssayDocType = apps.get_model("roadmap", "EssayDocType")
    EssayDocType.objects.filter(essays__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0005_phase41_application_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayDocType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True, verbose_name="Код")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("description", models.CharField(blank=True, max_length=250, verbose_name="Короткое описание")),
                (
                    "default_word_limit",
                    models.PositiveSmallIntegerField(default=650, verbose_name="Лимит слов по умолчанию"),
                ),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
            ],
            options={
                "verbose_name": "Тип документа эссе",
                "verbose_name_plural": "Типы документов эссе",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AddField(
            model_name="essay",
            name="word_limit",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Лимит слов"),
        ),
        migrations.CreateModel(
            name="EssayCheckQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=300, verbose_name="Вопрос")),
                ("option_a", models.CharField(max_length=250, verbose_name="Вариант A")),
                ("option_b", models.CharField(max_length=250, verbose_name="Вариант B")),
                ("option_c", models.CharField(blank=True, max_length=250, verbose_name="Вариант C")),
                ("option_d", models.CharField(blank=True, max_length=250, verbose_name="Вариант D")),
                ("correct", models.CharField(default="A", max_length=1, verbose_name="Верный вариант")),
                ("explanation", models.CharField(blank=True, max_length=400, verbose_name="Объяснение")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
                (
                    "doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_questions",
                        to="roadmap.essaydoctype",
                        verbose_name="Тип документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос проверки эссе",
                "verbose_name_plural": "Вопросы проверки эссе",
                "ordering": ("doc_type", "order", "id"),
            },
        ),
        migrations.AddField(
            model_name="essay",
            name="doc_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="essays",
                to="roadmap.essaydoctype",
                verbose_name="Тип документа",
            ),
        ),
        migrations.CreateModel(
            name="EssayExample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("source_url", models.URLField(blank=True, verbose_name="Ссылка")),
                ("body", models.TextField(blank=True, verbose_name="Текст примера")),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="Примечание")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "doc_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examples",
                        to="roadmap.essaydoctype",
                        verbose_name="Тип документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пример эссе",
                "verbose_name_plural": "Примеры эссе",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EssayGuide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("what_is", models.TextField(blank=True, verbose_name="Что это за документ")),
                (
                    "prompts",
                    models.TextField(blank=True, help_text="По одному в строке", verbose_name="Какие бывают вопросы"),
                ),
                ("mistakes", models.TextField(blank=True, help_text="По одной в строке", verbose_name="Частые ошибки")),
                ("tips", models.TextField(blank=True, help_text="По одному в строке", verbose_name="Советы")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "doc_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide",
                        to="roadmap.essaydoctype",
                        verbose_name="Тип документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гайд по эссе",
                "verbose_name_plural": "Гайды по эссе",
            },
        ),
            migrations.RunPython(seed_doc_types, unseed_doc_types),
    ]
