# Generated by Django 5.1.5 on 2026-08-31 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0006_phase43_essay_builder"),
        ("students", "0014_phase42_exam_types"),
        ("universities", "0009_phase44_scholarships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="scholarship",
            field=models.ForeignKey(
                blank=True,
                help_text="Если заполнено — срок берётся из дедлайна стипендии",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="universities.scholarship",
                verbose_name="Стипендия",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True), ("scholarship__isnull", False)),
                fields=("student", "scholarship"),
                name="uniq_task_per_scholarship",
            ),
        ),
    ]
