# Generated by Django 5.1.5 on 2026-09-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0007_phase44_scholarships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essay",
            name="essay_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal_statement", "Personal Statement"),
                    ("supplemental", "Дополнительное эссе"),
                    ("motivation", "Мотивационное письмо"),
                    ("scholarship", "Для стипендии"),
                    ("other", "Другое"),
                ],
                max_length=24,
                verbose_name="Тип",
            ),
        ),
    ]
