# Generated by Django 5.2.17 on 2026-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0009_phase61"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="author_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Автор на момент удаления"),
        ),
    ]
