# Generated by Django 5.2.17 on 2026-09-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0010_phase67"),
        ("students", "0026_document_superseded_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasktemplate",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="tasktemplate",
            name="graduation_year",
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="task_templates", to="students.studygroup", verbose_name="Группы"
            ),
        ),
    ]
