# Generated by Django 5.2.17 on 2026-10-08 08:22

import career.models
import django.db.models.deletion
import materials.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0033_author_trails_of_uploads"),
        ("universities", "0010_phase70_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField(verbose_name="Номер")),
                ("text", models.TextField(verbose_name="Текст")),
                ("sign", models.SmallIntegerField(default=1, verbose_name="Знак")),
            ],
            options={
                "verbose_name": "Вопрос теста",
                "verbose_name_plural": "Вопросы теста",
                "ordering": ("number", "id"),
            },
        ),
        migrations.CreateModel(
            name="CareerScale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, verbose_name="Код")),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Шкала теста",
                "verbose_name_plural": "Шкалы теста",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CareerAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fingerprint", models.CharField(db_index=True, max_length=200, verbose_name="Набор попыток")),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Идёт"), ("done", "Готов"), ("failed", "Не получился")],
                        default="running",
                        max_length=8,
                        verbose_name="Состояние",
                    ),
                ),
                ("language", models.CharField(default="ru", max_length=2, verbose_name="Язык разбора")),
                ("summary", models.TextField(blank=True, verbose_name="Общий вывод")),
                ("error", models.CharField(blank=True, max_length=300, verbose_name="Что пошло не так")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Запущен")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Готов")),
                ("visible_to_student", models.BooleanField(default=False, verbose_name="Показан ученику")),
                ("edited_at", models.DateTimeField(blank=True, null=True, verbose_name="Правил учитель")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто запустил",
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_career_analyses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто правил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_analyses",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разбор профтеста",
                "verbose_name_plural": "Разборы профтеста",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CareerAnalysisDirection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
                ("title", models.CharField(max_length=150, verbose_name="Направление")),
                ("reasoning", models.TextField(blank=True, verbose_name="Почему подходит")),
                ("professions", models.CharField(blank=True, max_length=300, verbose_name="Профессии")),
                ("subjects", models.CharField(blank=True, max_length=300, verbose_name="Какие предметы нужны")),
                ("exams", models.CharField(blank=True, max_length=300, verbose_name="Какие экзамены нужны")),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directions",
                        to="career.careeranalysis",
                    ),
                ),
                (
                    "programs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="career_analysis_directions",
                        to="universities.program",
                        verbose_name="Программы справочника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление разбора",
                "verbose_name_plural": "Направления разбора",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CareerAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "Идёт"), ("done", "Сдан")],
                        default="in_progress",
                        max_length=12,
                        verbose_name="Состояние",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Начат")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Сдан")),
                ("archived_at", models.DateTimeField(blank=True, null=True, verbose_name="В истории с")),
                (
                    "retake_allowed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_retakes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто разрешил пройти заново",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_attempts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка теста",
                "verbose_name_plural": "Попытки теста",
                "ordering": ("-started_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="careeranalysis",
            name="attempts",
            field=models.ManyToManyField(blank=True, related_name="analyses", to="career.careerattempt"),
        ),
        migrations.CreateModel(
            name="CareerItemChoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
                ("label", models.CharField(max_length=400, verbose_name="Текст варианта")),
                ("value", models.SmallIntegerField(default=1, verbose_name="Баллы")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="choices", to="career.careeritem"
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="choices", to="career.careerscale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант вопроса",
                "verbose_name_plural": "Варианты вопроса",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="careeritem",
            name="scale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="career.careerscale",
            ),
        ),
        migrations.CreateModel(
            name="CareerAttemptScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.SmallIntegerField(verbose_name="Балл")),
                ("label", models.CharField(blank=True, max_length=120, verbose_name="Интерпретация")),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scores", to="career.careerattempt"
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="scores", to="career.careerscale"
                    ),
                ),
            ],
            options={
                "verbose_name": "Балл по шкале",
                "verbose_name_plural": "Баллы по шкалам",
                "ordering": ("-score", "scale__order"),
            },
        ),
        migrations.CreateModel(
            name="CareerTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("instruction", models.TextField(blank=True, verbose_name="Инструкция")),
                ("analysis_min_score", models.SmallIntegerField(default=1, verbose_name="Порог для разбора")),
                ("is_active", models.BooleanField(default=False, verbose_name="Включён")),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        storage=materials.storage.private_storage,
                        upload_to=career.models.test_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=200, verbose_name="Имя файла")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Загружен")),
                ("archived_at", models.DateTimeField(blank=True, null=True, verbose_name="В архиве с")),
                ("is_fictional", models.BooleanField(default=False, verbose_name="Вымышленный")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест профориентации",
                "verbose_name_plural": "Тесты профориентации",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="careerscale",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="scales", to="career.careertest"
            ),
        ),
        migrations.CreateModel(
            name="CareerRange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("low", models.SmallIntegerField(verbose_name="От")),
                ("high", models.SmallIntegerField(verbose_name="До")),
                ("label", models.CharField(max_length=120, verbose_name="Подпись")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
                (
                    "scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranges",
                        to="career.careerscale",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ranges", to="career.careertest"
                    ),
                ),
            ],
            options={
                "verbose_name": "Диапазон интерпретации",
                "verbose_name_plural": "Диапазоны интерпретации",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="careeritem",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="items", to="career.careertest"
            ),
        ),
        migrations.AddField(
            model_name="careerattempt",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="career.careertest"
            ),
        ),
        migrations.CreateModel(
            name="CareerAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True, verbose_name="Назначен")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_assignments",
                        to="students.studygroup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_assignments",
                        to="students.student",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="career.careertest"
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение теста",
                "verbose_name_plural": "Назначения теста",
            },
        ),
        migrations.CreateModel(
            name="CareerTestOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=1, verbose_name="Порядок")),
                ("label", models.CharField(max_length=60, verbose_name="Подпись")),
                ("value", models.SmallIntegerField(verbose_name="Баллы")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="options", to="career.careertest"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CareerAttemptAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answered_at", models.DateTimeField(auto_now=True, verbose_name="Отвечен")),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="career.careerattempt"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="answers", to="career.careeritem"
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="career.careeritemchoice",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="career.careertestoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
            },
        ),
        migrations.AddIndex(
            model_name="careeranalysis",
            index=models.Index(fields=["student", "-created_at"], name="career_care_student_af4654_idx"),
        ),
        migrations.AddConstraint(
            model_name="careerattemptscore",
            constraint=models.UniqueConstraint(fields=("attempt", "scale"), name="uniq_career_score_scale"),
        ),
        migrations.AddConstraint(
            model_name="careerscale",
            constraint=models.UniqueConstraint(fields=("test", "code"), name="uniq_career_scale_code"),
        ),
        migrations.AddConstraint(
            model_name="careeritem",
            constraint=models.UniqueConstraint(fields=("test", "number"), name="uniq_career_item_number"),
        ),
        migrations.AddIndex(
            model_name="careerattempt",
            index=models.Index(fields=["student", "status"], name="career_care_student_16ab9b_idx"),
        ),
        migrations.AddConstraint(
            model_name="careerattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("test", "student"),
                name="uniq_career_attempt_live",
            ),
        ),
        migrations.AddConstraint(
            model_name="careerassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student__isnull", True)), fields=("test", "group"), name="uniq_career_assign_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="careerassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student__isnull", False)),
                fields=("test", "student"),
                name="uniq_career_assign_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="careertestoption",
            constraint=models.UniqueConstraint(fields=("test", "label"), name="uniq_career_option_label"),
        ),
        migrations.AddConstraint(
            model_name="careerattemptanswer",
            constraint=models.UniqueConstraint(fields=("attempt", "item"), name="uniq_career_answer_item"),
        ),
    ]
