# Generated by Django 5.2.17 on 2026-10-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careeranalysis",
            name="summary_student",
            field=models.TextField(blank=True, verbose_name="Общий вывод для ученика"),
        ),
        migrations.AddField(
            model_name="careeranalysisdirection",
            name="reasoning_student",
            field=models.TextField(blank=True, verbose_name="Почему подходит — для ученика"),
        ),
    ]
