# Generated by Django 5.1.5 on 2026-08-24 06:43

import django.db.models.deletion
import materials.models
import materials.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directories", "0001_phase18_directories"),
        ("students", "0007_phase19_materials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCollection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто собрал",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to="directories.olympiadsubject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подборка материалов",
                "verbose_name_plural": "Подборки материалов",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="MaterialComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к материалу",
                "verbose_name_plural": "Комментарии к материалам",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="MaterialRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("topic", models.CharField(max_length=200, verbose_name="Тема")),
                ("text", models.TextField(blank=True, verbose_name="Что именно нужно")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыт"), ("closed", "Закрыт")],
                        default="open",
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="Закрыт")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requests",
                        to="students.student",
                        verbose_name="Кто просит",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_requests",
                        to="directories.olympiadsubject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос материала",
                "verbose_name_plural": "Запросы материалов",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="В архиве с")),
                (
                    "archive_batch",
                    models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
                ),
                ("topic", models.CharField(max_length=200, verbose_name="Тема")),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("own_solution", "Моё решение"),
                            ("own_analysis", "Мой разбор"),
                            ("third_party", "Чужой материал"),
                        ],
                        max_length=16,
                        verbose_name="Тип источника",
                    ),
                ),
                (
                    "rights_confirmed",
                    models.BooleanField(default=False, verbose_name="Право на публикацию подтверждено"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Ждёт проверки"), ("approved", "Одобрен"), ("rejected", "Отклонён")],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("reject_reason", models.TextField(blank=True, verbose_name="Причина отклонения")),
                ("helpful_count", models.PositiveIntegerField(default=0, verbose_name="Отметок «было полезно»")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда проверен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Загружен")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="students.student",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="materials.materialrequest",
                        verbose_name="Закрывает запрос",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто проверил",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="directories.olympiadsubject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MaterialReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField(verbose_name="В чём дело")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Ждёт разбора"), ("resolved", "Разобрана")],
                        default="open",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("resolution", models.TextField(blank=True, verbose_name="Что сделали")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Разобрана")),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="materials.materialcomment",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто пожаловался",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="materials.studymaterial",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жалоба",
                "verbose_name_plural": "Жалобы",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MaterialHelpful",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpful_marks",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpful_marks",
                        to="materials.studymaterial",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отметка «было полезно»",
                "verbose_name_plural": "Отметки «было полезно»",
            },
        ),
        migrations.CreateModel(
            name="MaterialFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        storage=materials.storage.private_storage,
                        upload_to=materials.models.material_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                ("original_name", models.CharField(max_length=250, verbose_name="Имя файла")),
                ("content_type", models.CharField(max_length=100, verbose_name="Тип содержимого")),
                ("extension", models.CharField(max_length=10, verbose_name="Расширение")),
                ("size", models.PositiveIntegerField(verbose_name="Размер, байт")),
                ("checksum", models.CharField(max_length=64, verbose_name="Контрольная сумма")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Загружен")),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="materials.studymaterial",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл материала",
                "verbose_name_plural": "Файлы материалов",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="materialcomment",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="materials.studymaterial",
                verbose_name="Материал",
            ),
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="materials.materialcollection",
                        verbose_name="Подборка",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_collections",
                        to="materials.studymaterial",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал в подборке",
                "verbose_name_plural": "Материалы в подборках",
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="materialrequest",
            index=models.Index(fields=["status", "-created_at"], name="materials_m_status_10a14e_idx"),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(fields=["status", "-created_at"], name="materials_s_status_7b6fcf_idx"),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(fields=["subject", "status"], name="materials_s_subject_3c4c41_idx"),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(fields=["author", "-created_at"], name="materials_s_author__79e2c2_idx"),
        ),
        migrations.AddConstraint(
            model_name="materialreport",
            constraint=models.CheckConstraint(
                condition=models.Q(("material__isnull", False), ("comment__isnull", False), _connector="OR"),
                name="report_points_somewhere",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialhelpful",
            constraint=models.UniqueConstraint(fields=("material", "student"), name="uniq_helpful_per_student"),
        ),
        migrations.AddIndex(
            model_name="materialcomment",
            index=models.Index(fields=["material", "created_at"], name="materials_m_materia_352665_idx"),
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(fields=("collection", "material"), name="uniq_material_per_collection"),
        ),
    ]
