# Generated by Django 5.1.5 on 2026-08-25 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_phase19_materials"),
        ("students", "0009_phase30_parent_contacts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studymaterial",
            name="staff_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_materials",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор-сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="studymaterial",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="students.student",
                verbose_name="Автор",
            ),
        ),
    ]
