# Generated by Django 5.1.5 on 2026-08-31 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_categories(apps, schema_editor):
    """Семь стартовых категорий: это справочник, а не выдуманные данные."""
    ResourceCategory = apps.get_model("materials", "ResourceCategory")
    rows = (
        ("scholarships", "Стипендии", "Гранты, стипендии и как на них подаваться", "teal", 10),
        ("applications", "Заявки", "Как устроена подача: сроки, документы, порядок", "indigo", 20),
        ("universities", "Университеты", "Как выбирать вуз и на что смотреть", "brand", 30),
        ("prep", "Подготовка", "Экзамены, тренировки, планирование", "ok", 40),
        ("countries", "Страны", "Особенности учёбы и жизни по странам", "indigo", 50),
        ("olympiads", "Олимпиады", "Отбор, этапы, как готовиться", "warn", 60),
        ("sport", "Спорт", "Спортивные достижения в заявке", "ok", 70),
    )
    for code, name, description, accent, order in rows:
        ResourceCategory.objects.get_or_create(
            code=code, defaults={"name": name, "description": description, "accent": accent, "order": order}
        )


def unseed_categories(apps, schema_editor):
    ResourceCategory = apps.get_model("materials", "ResourceCategory")
    ResourceCategory.objects.filter(resources__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_phase31_competitions_and_staff_materials"),
        ("students", "0014_phase42_exam_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=40, unique=True, verbose_name="Код")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("description", models.CharField(blank=True, max_length=250, verbose_name="Описание")),
                (
                    "accent",
                    models.CharField(
                        blank=True,
                        help_text="brand, teal, indigo, ok, warn — токен из дизайн-системы",
                        max_length=16,
                        verbose_name="Цвет полосы",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Показывать")),
            ],
            options={
                "verbose_name": "Категория материалов",
                "verbose_name_plural": "Категории материалов",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("summary", models.CharField(blank=True, max_length=300, verbose_name="Короткое описание")),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                ("reading_minutes", models.PositiveSmallIntegerField(default=5, verbose_name="Время чтения, минут")),
                ("tags", models.CharField(blank=True, help_text="Через запятую", max_length=250, verbose_name="Метки")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Рекомендуем")),
                ("is_published", models.BooleanField(default=True, verbose_name="Показывать ученикам")),
                ("published_on", models.DateField(blank=True, null=True, verbose_name="Дата публикации")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="materials.resourcecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал раздела «Ресурсы»",
                "verbose_name_plural": "Материалы раздела «Ресурсы»",
                "ordering": ("-is_featured", "-published_on", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ResourceRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="materials.resource",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_reads",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прочитанный материал",
                "verbose_name_plural": "Прочитанные материалы",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["category", "is_published"], name="materials_r_categor_e2b591_idx"),
        ),
        migrations.AddConstraint(
            model_name="resourceread",
            constraint=models.UniqueConstraint(fields=("resource", "student"), name="uniq_resource_read"),
        ),
        migrations.RunPython(seed_categories, unseed_categories),
    ]
