# Generated by Django 5.1.5 on 2026-08-21 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roadmap", "0001_initial"),
        ("students", "0001_initial"),
        ("universities", "0002_admissionrequirement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alumnus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("graduation_year", models.PositiveSmallIntegerField(verbose_name="Год выпуска")),
                ("country", models.CharField(blank=True, max_length=100, verbose_name="Страна")),
                (
                    "current_occupation",
                    models.CharField(blank=True, max_length=250, verbose_name="Чем занимается сейчас"),
                ),
                (
                    "admission_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="GPA при поступлении"
                    ),
                ),
                (
                    "admission_ielts",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True, verbose_name="IELTS при поступлении"
                    ),
                ),
                (
                    "admission_sat",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="SAT при поступлении"),
                ),
                (
                    "admission_activities",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Активностей при поступлении"),
                ),
                ("mentorship_consent", models.BooleanField(default=False, verbose_name="Согласие на менторство")),
                ("contact_email", models.EmailField(blank=True, max_length=254, verbose_name="Контактная почта")),
                ("note", models.TextField(blank=True, verbose_name="Заметка школы")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumnus",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni",
                        to="universities.university",
                        verbose_name="Вуз",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выпускник",
                "verbose_name_plural": "Выпускники",
                "ordering": ("-graduation_year", "student__last_name"),
            },
        ),
        migrations.CreateModel(
            name="AlumnusApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("admitted", "Поступил"),
                            ("rejected", "Отказ"),
                            ("waitlist", "Лист ожидания"),
                            ("withdrawn", "Отозвал"),
                            ("enrolled", "Учится"),
                        ],
                        max_length=16,
                        verbose_name="Результат",
                    ),
                ),
                ("scholarship", models.CharField(blank=True, max_length=200, verbose_name="Стипендия")),
                ("note", models.CharField(blank=True, max_length=250, verbose_name="Примечание")),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="alumni.alumnus",
                        verbose_name="Выпускник",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alumni_applications",
                        to="universities.program",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка выпускника",
                "verbose_name_plural": "Заявки выпускников",
            },
        ),
        migrations.CreateModel(
            name="ArchivedEssay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("essay_type", models.CharField(max_length=24, verbose_name="Тип")),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("text", models.TextField(verbose_name="Текст")),
                ("consent_given", models.BooleanField(default=False, verbose_name="Согласие на публикацию")),
                ("consent_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда дано согласие")),
                ("is_anonymous", models.BooleanField(default=False, verbose_name="Скрыть имя автора")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_essays",
                        to="alumni.alumnus",
                        verbose_name="Выпускник",
                    ),
                ),
                (
                    "essay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_entries",
                        to="roadmap.essay",
                        verbose_name="Исходное эссе",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_essays",
                        to="universities.program",
                        verbose_name="Куда поступил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эссе в архиве",
                "verbose_name_plural": "Архив эссе",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MentorshipRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.CharField(max_length=250, verbose_name="Тема")),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Запрошено учеником"),
                            ("approved", "Одобрено школой"),
                            ("declined", "Отклонено школой"),
                            ("sent", "Передано выпускнику"),
                            ("accepted", "Выпускник согласился"),
                            ("refused", "Выпускник отказался"),
                            ("completed", "Завершено"),
                        ],
                        default="requested",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("is_visible_to_alumnus", models.BooleanField(default=False, verbose_name="Видно выпускнику")),
                ("review_note", models.CharField(blank=True, max_length=250, verbose_name="Решение сотрудника")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests",
                        to="alumni.alumnus",
                        verbose_name="Выпускник",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_mentorships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто рассмотрел",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorship_requests",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на менторство",
                "verbose_name_plural": "Запросы на менторство",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MentorshipMeeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Длительность, мин"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="О чём говорили")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="alumni.mentorshiprequest",
                        verbose_name="Запрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Встреча",
                "verbose_name_plural": "Встречи",
                "ordering": ("-date",),
            },
        ),
        migrations.AddIndex(
            model_name="alumnus",
            index=models.Index(fields=["graduation_year"], name="alumni_alum_graduat_88b61f_idx"),
        ),
        migrations.AddIndex(
            model_name="alumnus",
            index=models.Index(fields=["country"], name="alumni_alum_country_5cb3d8_idx"),
        ),
        migrations.AddIndex(
            model_name="alumnus",
            index=models.Index(fields=["mentorship_consent"], name="alumni_alum_mentors_31a2fb_idx"),
        ),
        migrations.AddConstraint(
            model_name="alumnusapplication",
            constraint=models.UniqueConstraint(fields=("alumnus", "program"), name="uniq_alumnus_program"),
        ),
        migrations.AddIndex(
            model_name="archivedessay",
            index=models.Index(fields=["consent_given"], name="alumni_arch_consent_244381_idx"),
        ),
        migrations.AddIndex(
            model_name="mentorshiprequest",
            index=models.Index(fields=["status", "-created_at"], name="alumni_ment_status_d368b5_idx"),
        ),
    ]
