# Generated by Django 5.1.5 on 2026-08-21 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suggestions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                ("model_label", models.CharField(max_length=100, verbose_name="Модель")),
                ("object_id", models.CharField(max_length=64, verbose_name="Объект")),
                ("student_id", models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="Ученик")),
                ("field_name", models.CharField(max_length=100, verbose_name="Поле")),
                ("domain_code", models.CharField(blank=True, max_length=32, verbose_name="Домен")),
                ("old_value", models.TextField(blank=True, verbose_name="Было")),
                ("new_value", models.TextField(blank=True, verbose_name="Стало")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Руками"), ("import", "Импорт"), ("ai", "ИИ"), ("sync", "Фоновая сверка")],
                        default="manual",
                        max_length=16,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто изменил",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="suggestions.suggestion",
                        verbose_name="Предложение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись аудита",
                "verbose_name_plural": "Журнал изменений",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["model_label", "object_id"], name="core_auditl_model_l_bd2fc4_idx"),
                    models.Index(fields=["-created_at"], name="core_auditl_created_1a76fa_idx"),
                    models.Index(fields=["domain_code", "-created_at"], name="core_auditl_domain__e79b71_idx"),
                ],
            },
        ),
    ]
