# Generated by Django 5.1.5 on 2026-08-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadinessSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата среза")),
                ("score", models.PositiveSmallIntegerField(verbose_name="Готовность, %")),
                (
                    "exam",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Экзамены"),
                ),
                (
                    "admission",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Поступление"
                    ),
                ),
                (
                    "talent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Портфолио"
                    ),
                ),
                (
                    "behavior",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Дисциплина"
                    ),
                ),
                (
                    "sport",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Спорт"),
                ),
                ("weakest", models.CharField(blank=True, max_length=32, verbose_name="Слабое звено")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readiness_snapshots",
                        to="students.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Срез готовности",
                "verbose_name_plural": "Срезы готовности",
                "ordering": ("-date",),
                "indexes": [models.Index(fields=["student", "-date"], name="core_readin_student_9be7c2_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("student", "date"), name="uniq_readiness_snapshot_per_day")
                ],
            },
        ),
    ]
