# Generated by Django 5.1.5 on 2026-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_readinesssnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Руками"),
                    ("import", "Импорт"),
                    ("ai", "ИИ"),
                    ("sync", "Фоновая сверка"),
                    ("student_onboarding", "Анкета ученика"),
                ],
                default="manual",
                max_length=32,
                verbose_name="Источник",
            ),
        ),
    ]
