# Generated by Django 5.1.5 on 2026-08-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="object_deleted",
            field=models.BooleanField(default=False, verbose_name="Объект удалён"),
        ),
    ]
