# Generated by Django 5.1.5 on 2026-08-23 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_audit_object_deleted"),
        ("suggestions", "0002_essayassistlog_llmcall"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch", models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="Номер удаления")),
                ("model_label", models.CharField(max_length=100, verbose_name="Модель")),
                ("object_id", models.CharField(max_length=64, verbose_name="Объект")),
                ("title", models.CharField(max_length=250, verbose_name="Что удалено")),
                ("kind_title", models.CharField(blank=True, max_length=100, verbose_name="Вид записи")),
                ("summary", models.CharField(blank=True, max_length=500, verbose_name="Что ушло вместе")),
                ("related_count", models.PositiveIntegerField(default=0, verbose_name="Связанных записей")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда удалено")),
                ("restored_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда восстановлено")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archive_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто удалил",
                    ),
                ),
                (
                    "restored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restored_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто восстановил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись архива",
                "verbose_name_plural": "Архив",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                ("file_name", models.CharField(blank=True, max_length=250, verbose_name="Файл")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("students", "Данные учеников"),
                            ("requirements", "Требования вузов"),
                            ("questions", "Банк заданий"),
                        ],
                        default="students",
                        max_length=16,
                        verbose_name="Что загружали",
                    ),
                ),
                ("domain_code", models.CharField(blank=True, max_length=32, verbose_name="Домен")),
                ("rows_total", models.PositiveIntegerField(default=0, verbose_name="Строк в файле")),
                ("rows_created", models.PositiveIntegerField(default=0, verbose_name="Создано записей")),
                ("rows_updated", models.PositiveIntegerField(default=0, verbose_name="Обновлено записей")),
                ("rows_failed", models.PositiveIntegerField(default=0, verbose_name="Строк с ошибкой")),
                (
                    "status",
                    models.CharField(
                        choices=[("applied", "Применена"), ("reverted", "Отменена"), ("partial", "Отменена частично")],
                        default="applied",
                        max_length=16,
                        verbose_name="Состояние",
                    ),
                ),
                ("reverted_at", models.DateTimeField(blank=True, null=True, verbose_name="Отменена")),
                ("note", models.CharField(blank=True, max_length=500, verbose_name="Примечание")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто загрузил",
                    ),
                ),
                (
                    "reverted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverted_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто отменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Загрузка файла",
                "verbose_name_plural": "История загрузок",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to="core.importbatch",
                verbose_name="Загрузка",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["import_batch", "-created_at"], name="core_auditl_import__9f8dee_idx"),
        ),
        migrations.AddIndex(
            model_name="archiveentry",
            index=models.Index(fields=["-created_at"], name="core_archiv_created_b340bb_idx"),
        ),
        migrations.AddIndex(
            model_name="archiveentry",
            index=models.Index(fields=["model_label", "object_id"], name="core_archiv_model_l_3598a8_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["-created_at"], name="core_import_created_564028_idx"),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(fields=["domain_code", "-created_at"], name="core_import_domain__7ee337_idx"),
        ),
    ]
