# Generated by Django 5.1.5 on 2026-08-24 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_archive_and_imports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("material_comment", "Комментарий к материалу"),
                            ("material_reviewed", "Материал проверен"),
                            ("material_pending", "Материал ждёт проверки"),
                            ("material_report", "Жалоба на материал"),
                            ("material_request", "Просят материал"),
                        ],
                        max_length=32,
                        verbose_name="Вид",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Текст")),
                ("link", models.CharField(blank=True, max_length=200, verbose_name="Куда ведёт")),
                ("is_read", models.BooleanField(default=False, verbose_name="Прочитано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кому",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["recipient", "is_read", "-created_at"], name="core_notifi_recipie_1d5476_idx")
                ],
            },
        ),
    ]
