# Generated by Django 5.1.5 on 2026-08-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_phase19_materials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveentry",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда удалено навсегда"),
        ),
        migrations.AddField(
            model_name="archiveentry",
            name="purged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purged_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто удалил навсегда",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="archive_batch",
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Номер удаления"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_purged",
            field=models.BooleanField(default=False, verbose_name="Удалён безвозвратно"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Имя на момент удаления"),
        ),
    ]
