# Generated by Django 5.1.5 on 2026-08-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_phase29_drop_alumni"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Автор на момент удаления"),
        ),
    ]
