# Generated by Django 5.1.5 on 2026-08-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_phase37_student_proposal_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("material_comment", "Комментарий к материалу"),
                    ("material_reviewed", "Материал проверен"),
                    ("material_pending", "Материал ждёт проверки"),
                    ("material_report", "Жалоба на материал"),
                    ("material_request", "Просят материал"),
                    ("event_reminder", "Напоминание о событии"),
                ],
                max_length=32,
                verbose_name="Вид",
            ),
        ),
    ]
