# Generated by Django 5.1.5 on 2026-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_phase39_event_reminder_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importbatch",
            name="kind",
            field=models.CharField(
                choices=[
                    ("students", "Данные учеников"),
                    ("requirements", "Требования вузов"),
                    ("questions", "Банк заданий"),
                    ("scholarships", "Стипендии"),
                ],
                default="students",
                max_length=16,
                verbose_name="Что загружали",
            ),
        ),
    ]
