# Generated by Django 5.1.5 on 2026-08-31 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_phase44_scholarships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("material_comment", "Комментарий к материалу"),
                    ("material_reviewed", "Материал проверен"),
                    ("material_pending", "Материал ждёт проверки"),
                    ("material_report", "Жалоба на материал"),
                    ("material_request", "Просят материал"),
                    ("event_reminder", "Напоминание о событии"),
                    ("job_done", "Фоновая операция закончилась"),
                    ("job_failed", "Фоновая операция не получилась"),
                ],
                max_length=32,
                verbose_name="Вид",
            ),
        ),
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=40, verbose_name="Вид операции")),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Идёт"), ("done", "Готово"), ("failed", "Не получилось")],
                        default="running",
                        max_length=8,
                        verbose_name="Состояние",
                    ),
                ),
                ("stage", models.CharField(blank=True, max_length=120, verbose_name="Этап")),
                ("percent", models.PositiveSmallIntegerField(default=0, verbose_name="Процент")),
                ("steps_done", models.PositiveSmallIntegerField(default=0, verbose_name="Пройдено этапов")),
                ("task_id", models.CharField(blank=True, db_index=True, max_length=64, verbose_name="Задача")),
                ("link", models.CharField(blank=True, max_length=200, verbose_name="Куда ведёт")),
                ("error", models.CharField(blank=True, max_length=300, verbose_name="Что пошло не так")),
                ("retry_task", models.CharField(blank=True, max_length=80, verbose_name="Задача для повтора")),
                ("retry_payload", models.TextField(blank=True, verbose_name="Аргументы повтора")),
                ("dismissed", models.BooleanField(default=False, verbose_name="Плашка скрыта")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Запущена")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Закончена")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто запустил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фоновая операция",
                "verbose_name_plural": "Фоновые операции",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["owner", "-created_at"], name="core_backgr_owner_i_b5ae8e_idx"),
                    models.Index(fields=["status"], name="core_backgr_status_896b38_idx"),
                ],
            },
        ),
    ]
