# Generated by Django 5.1.15 on 2026-09-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_phase47_background_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_role",
            field=models.CharField(blank=True, max_length=32, verbose_name="Роль автора на момент действия"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="student_group",
            field=models.CharField(blank=True, max_length=16, verbose_name="Группа ученика на момент действия"),
        ),
    ]
