# Generated by Django 5.1.15 on 2026-09-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_phase60"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("material_comment", "Комментарий к материалу"),
                    ("material_reviewed", "Материал проверен"),
                    ("material_pending", "Материал ждёт проверки"),
                    ("material_report", "Жалоба на материал"),
                    ("material_request", "Просят материал"),
                    ("event_reminder", "Напоминание о событии"),
                    ("job_done", "Фоновая операция закончилась"),
                    ("job_failed", "Фоновая операция не получилась"),
                    ("queue_decided", "Строку из вашей очереди решил владелец домена"),
                    ("document_reuploaded", "Ученик перезагрузил документ"),
                    ("document_expiring", "Срок документа истекает"),
                    ("escalation_answered", "Владелец домена ответил на переданное"),
                    ("escalation_request", "Куратор передал вопрос"),
                ],
                max_length=32,
                verbose_name="Вид",
            ),
        ),
    ]
