# Generated by Django 5.2.17 on 2026-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_phase62"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ciphertext", models.TextField(verbose_name="Шифртекст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
            ],
            options={
                "verbose_name": "Контрольная запись ключа",
                "verbose_name_plural": "Контрольные записи ключа",
            },
        ),
    ]
