# Generated by Django 5.2.17 on 2026-09-30 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_academics_notification_kinds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="Правило")),
                ("value", models.IntegerField(verbose_name="Значение")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Когда поменяли")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто поменял",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило школы",
                "verbose_name_plural": "Правила школы",
            },
        ),
    ]
