# Generated by Django 5.2.17 on 2026-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_school_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveentry",
            name="actor_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Кто удалил, на момент удаления"),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="actor_title",
            field=models.CharField(blank=True, max_length=250, verbose_name="Кто загрузил, на момент удаления"),
        ),
    ]
